global:
  <% if_p('alertmanager.resolve_timeout') do |resolve_timeout| %>
  resolve_timeout: <%= resolve_timeout %>
  <% end %>

  <% if_p('alertmanager.smtp.from') do |from| %>
  smtp_from: <%= from %>
  <% end %>

  <% if_p('alertmanager.smtp.smarthost') do |smarthost| %>
  smtp_smarthost: <%= smarthost %>
  <% end %>

  <% if_p('alertmanager.smtp.hello') do |hello| %>
  smtp_hello: <%= hello %>
  <% end %>

  <% if_p('alertmanager.smtp.auth_username') do |auth_username| %>
  smtp_auth_username: <%= auth_username %>
  <% end %>

  <% if_p('alertmanager.smtp.auth_password') do |auth_password| %>
  smtp_auth_password: <%= auth_password %>
  <% end %>

  <% if_p('alertmanager.smtp.auth_secret') do |auth_secret| %>
  smtp_auth_secret: <%= auth_secret %>
  <% end %>

  <% if_p('alertmanager.smtp.auth_identity') do |auth_identity| %>
  smtp_auth_identity: <%= auth_identity %>
  <% end %>

  <% if_p('alertmanager.smtp.require_tls') do |require_tls| %>
  smtp_require_tls: <%= require_tls %>
  <% end %>

  <% if_p('alertmanager.slack.api_url') do |api_url| %>
  slack_api_url: <%= api_url %>
  <% end %>

  <% if_p('alertmanager.victorops.api_key') do |api_key| %>
  victorops_api_key: <%= api_key %>
  <% end %>

  <% if_p('alertmanager.victorops.api_url') do |api_url| %>
  victorops_api_url: <%= api_url %>
  <% end %>

  <% if_p('alertmanager.pagerduty.url') do |url| %>
  pagerduty_url: <%= url %>
  <% end %>

  <% if_p('alertmanager.jira.url') do |jira_url| %>
  jira_api_url: <%= jira_url %>
  <% end %>

  <% if_p('alertmanager.opsgenie.api_host') do |api_host| %>
  opsgenie_api_url: <%= api_host %>
  <% end %>

  <% if_p('alertmanager.opsgenie.api_key') do |api_key| %>
  opsgenie_api_key: <%= api_key %>
  <% end %>

  <% if_p('alertmanager.wechat.api_url') do |api_url| %>
  wechat_api_url: <%= api_url %>
  <% end %>

  <% if_p('alertmanager.wechat.api_secret') do |api_secret| %>
  wechat_api_secret: <%= api_secret %>
  <% end %>

  <% if_p('alertmanager.wechat.api_corp_id') do |api_corp_id| %>
  wechat_api_corp_id: <%= api_corp_id %>
  <% end %>

  <% if_p('alertmanager.http_config') do |http_config| %>
  http_config: <%= http_config.to_json %>
  <% end %>

# The directory from which notification templates are read.
templates:
  <% p('alertmanager.templates', []).each do |template_path| %>
  <%= "- #{template_path}" %>
  <% end %>

# The root node of the routing tree
route:
  receiver: <%= p('alertmanager.route.receiver') %>

  <% if_p('alertmanager.route.continue') do |continue| %>
  continue: <%= continue %>
  <% end %>

  <% if_p('alertmanager.route.group_by') do |group_by| %>
  group_by: <%= group_by %>
  <% end %>

  <% if_p('alertmanager.route.group_wait') do |group_wait| %>
  group_wait: <%= group_wait %>
  <% end %>

  <% if_p('alertmanager.route.group_interval') do |group_interval| %>
  group_interval: <%= group_interval %>
  <% end %>

  <% if_p('alertmanager.route.repeat_interval') do |repeat_interval| %>
  repeat_interval: <%= repeat_interval %>
  <% end %>

  <% if_p('alertmanager.route.match') do |match| %>
  match: <%= match.to_json %>
  <% end %>

  <% if_p('alertmanager.route.match_re') do |match_re| %>
  match_re: <%= match_re.to_json %>
  <% end %>

  <% if_p('alertmanager.route.matchers') do |matchers| %>
  matchers: <%= matchers.to_json %>
  <% end %>

  # Child routes
  routes: <%= p('alertmanager.route.routes', []).to_json %>

# A list of notification receivers
receivers: <%= p('alertmanager.receivers').to_json %>

<% if_p('alertmanager.inhibit_rules') do |inhibit_rules| %>
# A list of inhibition rules
inhibit_rules: <%= inhibit_rules.to_json %>
<% end %>

<% if_p('alertmanager.mute_time_intervals') do |mute_time_intervals| %>
# A list of mute time intervals
mute_time_intervals: <%= mute_time_intervals.to_json %>
<% end %>

<% if_p('alertmanager.time_intervals') do |time_intervals| %>
# A list of time intervals
time_intervals: <%= time_intervals.to_json %>
<% end %>
