{
 "title": "P-RabbitMQ: Overview",
 "tags": [ "RabbitMQ" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_heartbeat, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_heartbeat{environment=~\"$environment\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_heartbeat{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}, bosh_job_name)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_heartbeat{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_heartbeat{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "vHosts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_vhosts_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_connections_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Erlang Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_erlang_erlang_processes{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_channels_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_consumers_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_exchanges_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_queues_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_available{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_delivered{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Delivered"
    },
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_pending{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_published{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Published"
    },
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_redelivered{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Redelivered"
    },
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_get_no_ack{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Get noack"
    },
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_delivered_noack{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Delivered noack"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_delivered_rate{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Delivered"
    },
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_get_no_ack_rate{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Get noack"
    },
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_published_rate{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Published"
    },
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_redelivered_rate{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Redelivered"
    }
   ]
  }
 ]
}