{
 "title": "P-RabbitMQ: HAProxy",
 "tags": [ "RabbitMQ" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_value_metric_p_rabbitmq_p_rabbitmq_haproxy_heartbeat, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_value_metric_p_rabbitmq_p_rabbitmq_haproxy_heartbeat{environment=~\"$environment\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(firehose_value_metric_p_rabbitmq_p_rabbitmq_haproxy_heartbeat{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}, bosh_job_name)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(firehose_value_metric_p_rabbitmq_p_rabbitmq_haproxy_heartbeat{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "HAProxy Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(firehose_value_metric_p_rabbitmq_p_rabbitmq_haproxy_heartbeat{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Health Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_haproxy_health_connections{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\",bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Backend Ctime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_haproxy_backend_ctime_amqp{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "ctime"
    }
   ]
  },
  {
   "title": "Backend Retries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_haproxy_backend_retries_amqp{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Retries"
    }
   ]
  },
  {
   "title": "Backend Qsize",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_rabbitmq_p_rabbitmq_haproxy_backend_qsize_amqp{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "qsize"
    }
   ]
  }
 ]
}