{
 "title": "Concourse: Overview",
 "tags": [ "concourse" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_deployment_release_info{bosh_release_name=\"concourse\"}, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Worker Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" }
     ],
     "measurement": "worker containers",
     "query": "SELECT mean(\"value\") FROM \"cpu\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/^$bosh_deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bosh_job_load_avg01{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"worker\"}",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Worker Volumes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "worker: [[tag_worker]]",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" }
     ],
     "measurement": "worker volumes",
     "query": "SELECT mean(\"value\") FROM \"cpu\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/^$bosh_deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bosh_job_persistent_disk_percent{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"worker\"}",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Scheduling: Full",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_pipeline]]",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "pipeline" ], "type": "tag" }
     ],
     "groupByTags": [ "pipeline" ],
     "measurement": "scheduling: full duration (ms)",
     "query": "SELECT mean(value) FROM \"scheduling: full duration (ms)\" WHERE $timeFilter GROUP BY time($dynamic), \"pipeline\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/^$bosh_deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "database connections",
     "query": "SELECT mean(\"value\") FROM \"scheduling: loading versions duration (ms)\" WHERE $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/^$bosh_deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Database Queries (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "database queries",
     "query": "SELECT non_negative_derivative(max(\"value\"), 10s) FROM \"database queries\" WHERE $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/^$bosh_deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Response Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_route]]",
     "fields": [
      { "func": "max", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "groupByTags": [ "route" ],
     "measurement": "http response time",
     "query": "SELECT mean(\"value\") FROM \"http response time\" WHERE $timeFilter GROUP BY time($interval), \"route\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/^$bosh_deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Web Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bosh_job_mem_percent{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"web\"}",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Web CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bosh_job_cpu_user{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"web\"}",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Web Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "groupByTags": [ "host" ],
     "measurement": "goroutines",
     "query": "SELECT mean(\"value\") * 100 FROM \"cpu\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=", "value": "web" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/^$bosh_deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bosh_job_mem_percent{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"worker\"}",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Worker CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bosh_job_cpu_user{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"worker\"}",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Worker Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{device=\"eth0\"}[5m]) *on(instance) group_left(bosh_job_ip) node_role{bosh_deployment=~\"$bosh_deployment\", bosh_job_name=\"worker\"}",
     "legendFormat": "{{bosh_job_ip}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes{device=\"eth0\"}[5m]) *on(instance) group_left(bosh_job_ip) node_role{bosh_deployment=~\"$bosh_deployment\", bosh_job_name=\"worker\"}",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  }
 ]
}