{
 "title": "P-Redis: Overview",
 "tags": [ "Redis" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_value_metric_p_redis_p_redis_info_server_uptime_in_seconds, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_value_metric_p_redis_p_redis_info_server_uptime_in_seconds{environment=~\"$environment\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(firehose_value_metric_p_redis_p_redis_info_server_uptime_in_seconds{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}, bosh_job_name)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(firehose_value_metric_p_redis_p_redis_info_server_uptime_in_seconds{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_server_uptime_in_seconds{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_clients_connected_clients{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Clients Blocked",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_clients_blocked_clients{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Rejected Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_stats_rejected_connections{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Commands Processed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_stats_total_commands_processed{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Last Save To Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - avg(firehose_value_metric_p_redis_p_redis_info_persistence_rdb_last_save_time{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Hit Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_stats_keyspace_hits{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"}) / (avg(firehose_value_metric_p_redis_p_redis_info_stats_keyspace_hits{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"}) + avg(firehose_value_metric_p_redis_p_redis_info_stats_keyspace_misses{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"}))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_stats_keyspace_hits{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Hits"
    },
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_stats_keyspace_misses{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Misses"
    },
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_stats_expired_keys{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Expired"
    },
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_stats_evicted_keys{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Instantaneous Ops per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_p_redis_p_redis_info_stats_instantaneous_ops_per_sec{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"}",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Instantaneous Ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_stats_instantaneous_input_kbps{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Input"
    },
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_stats_instantaneous_output_kbps{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Changes Since Last Save",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_persistence_rdb_changes_since_last_save{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Changes"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_clients_connected_clients{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "title": "Memory Fragmentation Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_memory_mem_fragmentation_ratio{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Memory Fragmentation"
    }
   ]
  },
  {
   "title": "Persistence Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_persistence_aof_last_rewrite_time_sec{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "AOF rewrite"
    },
    {
     "expr": "avg(firehose_value_metric_p_redis_p_redis_info_persistence_rdb_last_bgsave_time_sec{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "RDB bgsave"
    }
   ]
  }
 ]
}