{
 "title": "P-Redis: redis-metrics",
 "tags": [ "Redis" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_value_metric_p_redis_num_cpus, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_value_metric_p_redis_num_cpus{environment=~\"$environment\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(firehose_value_metric_p_redis_num_cpus{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}, bosh_job_name)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(firehose_value_metric_p_redis_num_cpus{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPUs",
   "type": "graph",
   "description": "Number of CPUs on the machine.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_num_cpus{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "CPUs"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "description": "Instantaneous number of active goroutines in the process.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_num_go_routines{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Go Routines"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Instantaneous count of bytes allocated and still in use.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_memory_stats_num_bytes_allocated{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Stack Allocator Memory Usage",
   "type": "graph",
   "description": "Instantaneous count of bytes used by the stack allocator.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_memory_stats_num_bytes_allocated_stack{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Main Heap Memory Usage",
   "type": "graph",
   "description": "Instantaneous count of bytes allocated on the main heap and still in use.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_memory_stats_num_bytes_allocated_heap{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Main Heap Memory"
    }
   ]
  },
  {
   "title": "Garbage Collector Pause Duration",
   "type": "graph",
   "description": "Duration in nanoseconds of the last garbage collector pause.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_memory_stats_last_gc_pause_time_ns{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "# of Memory Allocations",
   "type": "graph",
   "description": "Lifetime number of memory allocations.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_memory_stats_num_mallocs{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "# of Memory Allocations"
    }
   ]
  },
  {
   "title": "# of Memory Deallocations",
   "type": "graph",
   "description": "Lifetime number of memory deallocations.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_p_redis_memory_stats_num_frees{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"$bosh_job_name\", bosh_job_ip=~\"$host\"})",
     "legendFormat": "# of Memory Deallocations"
    }
   ]
  }
 ]
}