# This file assumes bosh_exporter based Service Discovery is being used: ./monitor-bosh.yml

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: postgres_exporter
    release: prometheus
    properties:
      postgres_exporter:
        datasource_name: "((postgres_datasource_name))"

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=postgres_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/postgres_alerts/*.alerts.yml

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=postgres_dashboards?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=PostgreSQL?/files/-
  value: /var/vcap/jobs/postgres_dashboards/*.json
