# This file assumes bosh_exporter based Service Discovery is being used: ./monitor-bosh.yml

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus/jobs/-
  value:
    name: mongodb_exporter
    release: prometheus
    properties:
      mongodb_exporter:
        mongodb:
          uri: "((mongodb_uri))"

#Grafana dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=mongodb_dashboards?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=MongoDB?/files/-
  value: /var/vcap/jobs/mongodb_dashboards/*.json
