# This file assumes bosh_exporter based Service Discovery is being used: ./monitor-bosh.yml

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus/jobs/-
  value:
    name: rabbitmq_exporter
    release: prometheus
    properties:
      rabbitmq_exporter:
        rabbitmq:
          url: "((rabbitmq_url))"
          user: "((rabbitmq_user))"
          password: "((rabbitmq_password))"

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=rabbitmq_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/rabbitmq_alerts/*.alerts.yml

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=rabbitmq_dashboards?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=RabbitMQ?/files/-
  value: /var/vcap/jobs/rabbitmq_dashboards/*.json
