tls_server_config:
  cert_file: /var/vcap/jobs/mongodb_exporter/config/web_tls_cert.pem
  key_file: /var/vcap/jobs/mongodb_exporter/config/web_tls_key.pem
<% if_p('mongodb_exporter.web.tls_client_ca') do %>
  client_ca_file: /var/vcap/jobs/mongodb_exporter/config/web_tls_client_ca.pem
<% end %>