{
 "title": "Concourse: Pipelines",
 "tags": [ "concourse" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(concourse_builds_finished, bosh_deployment)"
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "label_values(concourse_builds_finished{bosh_deployment=~\"$bosh_deployment\"}, pipeline)"
   }
  ]
 },
 "panels": [
  {
   "title": "Scheduling: Full",
   "type": "graph",
   "description": "Last time taken to schedule an entire pipeline",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "#Valid until concourse 4.2.1\nmax(concourse_scheduling_full_duration_seconds{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}) by(bosh_deployment, pipeline)",
     "legendFormat": "Duration"
    },
    {
     "expr": "#Valid starting concourse 4.2.2 and 5.x\nmax(concourse_scheduling_full_duration_seconds_total{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}) by(bosh_deployment, pipeline)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Scheduling: Loading",
   "type": "graph",
   "description": "Last time taken to load version information from the database for a pipeline",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "#Valid until concourse 4.2.1\nmax(concourse_scheduling_loading_duration_seconds{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}) by(bosh_deployment, pipeline)",
     "legendFormat": "Duration"
    },
    {
     "expr": "#Valid starting concourse 4.2.2 and 5.x\nmax(concourse_scheduling_loading_duration_seconds_total{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}) by(bosh_deployment, pipeline)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Scheduling: Job",
   "type": "graph",
   "description": "Last time taken to calculate the set of valid input versions for a pipeline. Not present anymore in concourse 5.x",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "#Valid until concourse 4.2.1\nmax(concourse_scheduling_job_duration_seconds{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}) by(bosh_deployment, pipeline)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Builds Finished",
   "type": "graph",
   "description": "Count of builds finished",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_builds_finished{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}) by(bosh_deployment, pipeline, status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Build Duration",
   "type": "graph",
   "description": "Build time",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n  rate(concourse_builds_duration_seconds_sum{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}[5m]) / \n  rate(concourse_builds_duration_seconds_count{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}[5m])\n) by(bosh_deployment, pipeline)",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}