{
 "title": "Ingestors",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(ingestor_up, environment)"
   }
  ]
 },
 "panels": [
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Publish Rate (All Ingestors Combined)",
   "type": "graph",
   "description": "Number of messages successfully sent to syslog endpoint per second  (all ingestors combined).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingestor_publish_total{environment=~\"$env\"}[5m])) by (environment)",
     "legendFormat": "{{ environment }}"
    }
   ]
  },
  {
   "title": "Publish Rate",
   "type": "graph",
   "description": "Number of messages successfully sent to syslog endpoint per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ingestor_publish_total{environment=~\"$env\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Messages in Buffer",
   "type": "graph",
   "description": "Number of messages in buffer. Ideally values should be close to 0. If values are infinitely increasing, this may be a sign that you need to scale up/out your ingestors. If the ingestor's buffer overfills, you'll likely see the values plateau at a non-zero value. In this case, displayed values are higher than they actually are. If you suspect this is the case you may want to restart ingestors and perhaps even increase the max-buffer-size of your ingestors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ingestor_subinupt_buffer{environment=~\"$env\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Message Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Log-Message Rate",
   "type": "graph",
   "description": "Number of Log messages received per second.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ingestor_consume_log_message_total{environment=~\"$env\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Http-Start-Stop Rate",
   "type": "graph",
   "description": "Number of Http-Start-Stop messages received per second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ingestor_consume_http_start_stop_total{environment=~\"$env\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Container-Metric Rate",
   "type": "graph",
   "description": "Number of Container-Metric messages received per second.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ingestor_consume_container_metric_total{environment=~\"$env\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Counter-Event Rate",
   "type": "graph",
   "description": "Number of CounterEvent messages received per second.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ingestor_consume_counter_event_total{environment=~\"$env\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Value-Metric Rate",
   "type": "graph",
   "description": "ValueMetric messages received per second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ingestor_consume_value_metric_total{environment=~\"$env\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Error-Event Rate",
   "type": "graph",
   "description": "Error-Events received per second.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ingestor_consume_error_total{environment=~\"$env\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ignore Rate",
   "type": "graph",
   "description": "Messages dropped per second due to no forwarding rule.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ingestor_ignored_total{environment=~\"$env\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Ingestor Up",
   "type": "graph",
   "description": "Are ingestors up and reachable?\n\n1=up; 0=down.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ingestor_up{environment=~\"$env\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ingestor Health",
   "type": "graph",
   "description": "Are we getting 200 response codes from ingestors?\n\n1= healthy; 0=unhealthy",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ingestor_healthy{environment=~\"$env\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}