{
 "title": "Probe: HTTPS Summary",
 "tags": [ "probe" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "Target",
    "query": "label_values(probe_success, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "description": "Is the target responding?",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(probe_success{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Current Response Time",
   "type": "singlestat",
   "description": "Current response time for this target.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "description": "Is SSL enabled for this target?",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_http_ssl{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "SSL Cert Expiration",
   "type": "singlestat",
   "description": "If SSL is enabled, when are the certs going to expire?",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{instance=~\"$target\"}) - time()"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "description": "Response time for this target.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "graph",
   "description": "Response status code for this target.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(probe_http_status_code{instance=~\"$target\"})",
     "legendFormat": "Status Code"
    }
   ]
  }
 ]
}