{
 "title": "MySQL: Replication",
 "tags": [ "MySQL" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{bosh_job_name=\"mysql\"}, bosh_deployment)"
   },
   {
    "name": "galeranode",
    "label": "Galera-node",
    "query": "label_values(bosh_job_healthy{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"mysql\"}, bosh_job_ip)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up{instance=~\"$galeranode:.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "IO Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_slave_status_slave_io_running{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "SQL Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_slave_status_slave_sql_running{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Replication Error No",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_slave_status_last_errno{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_read_only{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "MySQL Replication Delay",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_slave_status_seconds_behind_master{instance=\"$host\"}",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Binlogs Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_binlog_size_bytes{instance=\"$host\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Binlog Data Written Hourly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_binlog_size_bytes{instance=\"$host\"}[1h])",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Binlogs Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_binlog_files{instance=\"$host\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Binlogs Created Hourly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_binlog_file_number{instance=\"$host\"}[1h])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Relay Log Space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_slave_status_relay_log_space{instance=\"$host\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Relay Log Written Hourly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_slave_status_relay_log_space{instance=\"$host\"}[1h])",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}