{
 "title": "MySQL: Galera",
 "tags": [ "MySQL" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{bosh_job_name=\"mysql\"}, bosh_deployment)"
   },
   {
    "name": "galeranode",
    "label": "Galera-node",
    "query": "label_values(bosh_job_healthy{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"mysql\"}, bosh_job_ip)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up{instance=~\"$galeranode:.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_size{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Operational",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_status{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_ready{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_connected{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Flow Control Pause",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_flow_control_paused{instance=~\"$host\"}",
     "legendFormat": "Flow Control Pause"
    }
   ]
  },
  {
   "title": "Avg Length Send Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_local_send_queue_avg{instance=~\"$host\"}",
     "legendFormat": "Avg Length Send Queue"
    }
   ]
  },
  {
   "title": "Avg Length Receive Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_local_recv_queue_avg{instance=~\"$host\"}",
     "legendFormat": "Avg Length Receive Queue"
    }
   ]
  }
 ]
}