{
 "title": "MySQL: InnoDB Metrics",
 "tags": [ "MySQL" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{bosh_job_name=\"mysql\"}, bosh_deployment)"
   },
   {
    "name": "galeranode",
    "label": "Galera-node",
    "query": "label_values(bosh_job_healthy{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"mysql\"}, bosh_job_ip)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up{instance=~\"$galeranode:.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "InnoDB Checkpoint Age",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_checkpoint_age{instance=\"$host\"}",
     "legendFormat": "Uncheckpointed Bytes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_checkpoint_max_age{instance=\"$host\"}",
     "legendFormat": "Max Checkpoint Age"
    }
   ]
  },
  {
   "title": "InnoDB Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_max_trx_id{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_max_trx_id{instance=\"$host\"}[5m])",
     "legendFormat": "InnoDB Transactions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_history_list_length{instance=\"$host\"} or mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len{instance=\"$host\"}",
     "legendFormat": "History Length"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_max_purge_lag{instance=\"$host\"}",
     "legendFormat": "Max Purge Lag"
    }
   ]
  },
  {
   "title": "InnoDB Row Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\"}[5m])",
     "legendFormat": "Rows {{ operation }}"
    }
   ]
  },
  {
   "title": "InnoDB Row Lock Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_lock_waits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_lock_waits{instance=\"$host\"}[5m])",
     "legendFormat": "Row Lock Waits"
    },
    {
     "expr": "rate(mysql_global_status_innodb_row_lock_time{instance=\"$host\"}[$interval])/1000 or irate(mysql_global_status_innodb_row_lock_time{instance=\"$host\"}[5m])/1000",
     "legendFormat": "Row Lock Wait Load"
    },
    {
     "expr": "rate(mysql_global_status_innodb_row_lock_time{instance=\"$host\"}[$interval])/rate(mysql_global_status_innodb_row_lock_waits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_lock_time{instance=\"$host\"}[5m])/irate(mysql_global_status_innodb_row_lock_waits{instance=\"$host\"}[5m])",
     "legendFormat": "Avg Row Lock Wait Time"
    }
   ]
  },
  {
   "title": "InnoDB I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_data_reads{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{instance=\"$host\"}[5m])",
     "legendFormat": "Data Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_data_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{instance=\"$host\"}[5m])",
     "legendFormat": "Data Writes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_data_fsyncs{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_fsyncs{instance=\"$host\"}[5m])",
     "legendFormat": "Data Fsyncs"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_log_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_log_writes{instance=\"$host\"}[5m])",
     "legendFormat": "Log Writes"
    }
   ]
  },
  {
   "title": "InnoDB Log File Usage Hourly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_innodb_os_log_written{instance=\"$host\"}[1h])",
     "legendFormat": "Data Written"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_log_files_in_group{instance=\"$host\"} * mysql_global_variables_innodb_log_file_size{instance=\"$host\"}",
     "legendFormat": "Total Size of InnoDB Log Files"
    }
   ]
  },
  {
   "title": "InnoDB Deadlocks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_innodb_deadlocks{instance=\"$host\"}[$interval]) or rate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{instance=\"$host\"}[$interval])) or (irate(mysql_global_status_innodb_deadlocks{instance=\"$host\"}[5m]) or irate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{instance=\"$host\"}[5m]))",
     "legendFormat": "Deadlocks"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Pages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_buffer_pool_pages{instance=\"$host\", state!=\"dirty\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Content",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_data{instance=\"$host\"}",
     "legendFormat": "Data Total"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_dirty{instance=\"$host\"}",
     "legendFormat": "Data Dirty"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Read Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_write_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Write Requests"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_pages_created{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_created{instance=\"$host\"}[5m])",
     "legendFormat": "Pages Created"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_pages_read{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_read{instance=\"$host\"}[5m])",
     "legendFormat": "Pages Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_pages_written{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_written{instance=\"$host\"}[5m])",
     "legendFormat": "Pages Written"
    }
   ]
  },
  {
   "title": "InnoDB Change Buffer Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_ibuf_merges{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merges{instance=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{instance=\"$host\"}[5m])",
     "legendFormat": "Merges"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_ibuf_merged_inserts{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_inserts{instance=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{instance=\"$host\"}[5m])",
     "legendFormat": "Merged Inserts"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_ibuf_merged_deletes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_deletes{instance=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{instance=\"$host\"}[5m])",
     "legendFormat": "Merged Deletes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_ibuf_merged_delete_marks{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_delete_marks{instance=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{instance=\"$host\"}[5m])",
     "legendFormat": "Merged Delete Marks"
    }
   ]
  },
  {
   "title": "InnoDB Change Buffer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_ibuf_segment_size{instance=\"$host\"} * mysql_global_status_innodb_page_size{instance=\"$host\"}",
     "legendFormat": "Allocated"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(mysql_global_status_innodb_ibuf_segment_size{instance=\"$host\"} - mysql_global_status_innodb_ibuf_free_list{instance=\"$host\"})*mysql_global_status_innodb_page_size{instance=\"$host\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}