{
 "title": "MySQL: MyISAM Metrics",
 "tags": [ "MySQL" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{bosh_job_name=\"mysql\"}, bosh_deployment)"
   },
   {
    "name": "galeranode",
    "label": "Galera-node",
    "query": "label_values(bosh_job_healthy{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"mysql\"}, bosh_job_ip)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up{instance=~\"$galeranode:.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "MyISAM Indexes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_reads{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_reads{instance=\"$host\"}[5m])",
     "legendFormat": "Key Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_read_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_read_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Key Read Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_writes{instance=\"$host\"}[5m])",
     "legendFormat": "Key Writes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_write_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_write_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Key Write Requests"
    }
   ]
  },
  {
   "title": "MyISAM Key Cache",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$host\"}",
     "legendFormat": "Key Buffer Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$host\"} - mysql_global_status_key_blocks_unused{instance=\"$host\"} * mysql_global_variables_key_cache_block_size{instance=\"$host\"}",
     "legendFormat": "Key Blocks Used"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_key_blocks_not_flushed{instance=\"$host\"} * mysql_global_variables_key_cache_block_size{instance=\"$host\"}",
     "legendFormat": "Key Blocks Not Flushed"
    }
   ]
  },
  {
   "title": "MyISAM Key Buffer Performance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_reads{instance=\"$host\"}[$interval]) / rate(mysql_global_status_key_read_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_reads{instance=\"$host\"}[5m]) / irate(mysql_global_status_key_read_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Key Read Ratio"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_writes{instance=\"$host\"}[$interval]) / rate(mysql_global_status_key_write_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_writes{instance=\"$host\"}[5m]) / irate(mysql_global_status_key_write_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Key Write Ratio"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "content": "The `Key_reads/Key_read_requests` ratio should normally be less than 0.01.\n\nThe `Key_writes/Key_write_requests` ratio is usually near 1 if you are using mostly updates and deletes, but might be much smaller if you tend to do updates that affect many rows at the same time or if you are using the `DELAY_KEY_WRITE` table option."
  }
 ]
}