{
 "title": "MySQL: InnoDB Metrics Advanced",
 "tags": [ "MySQL" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{bosh_job_name=\"mysql\"}, bosh_deployment)"
   },
   {
    "name": "galeranode",
    "label": "Galera-node",
    "query": "label_values(bosh_job_healthy{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"mysql\"}, bosh_job_ip)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up{instance=~\"$galeranode:.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Change Buffer Performance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{instance=\"$host\"}[5m])",
     "legendFormat": "Ibuf Insert"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{instance=\"$host\"}[5m])",
     "legendFormat": "Ibuf Delete"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{instance=\"$host\"}[5m])",
     "legendFormat": "Ibuf Delete Mark"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{instance=\"$host\"}[5m])",
     "legendFormat": "Ibuf Merges"
    },
    {
     "expr": "(rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{instance=\"$host\"}[$interval])+rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{instance=\"$host\"}[$interval])+rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{instance=\"$host\"}[$interval]))/rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{instance=\"$host\"}[$interval]) or (irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{instance=\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{instance=\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{instance=\"$host\"}[5m]))/irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{instance=\"$host\"}[5m])",
     "legendFormat": "Ibuf Merge Ratio"
    }
   ]
  },
  {
   "title": "InnoDB Log Buffer Performance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=\"$host\"}*0 + on (instance) mysql_global_variables_innodb_log_buffer_size{instance=\"$host\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=\"$host\"} - mysql_info_schema_innodb_metrics_recovery_log_lsn_last_flush{instance=\"$host\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "InnoDB Purge Performance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_purge_purge_upd_exist_or_extern_records_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_purge_purge_upd_exist_or_extern_records_total{instance=\"$host\"}[5m])",
     "legendFormat": "Updates Purged"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_purge_purge_del_mark_records_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_purge_purge_del_mark_records_total{instance=\"$host\"}[5m])",
     "legendFormat": "Deletes Purged"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_purge_purge_undo_log_pages_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_purge_purge_undo_log_pages_total{instance=\"$host\"}[5m])",
     "legendFormat": "Pages Purged"
    }
   ]
  },
  {
   "title": "InnoDB Locking",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_created_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_created_total{instance=\"$host\"}[5m])",
     "legendFormat": "Locks Created"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_removed_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_removed_total{instance=\"$host\"}[5m])",
     "legendFormat": "Locks Removed"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_requests_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_requests_total{instance=\"$host\"}[5m])",
     "legendFormat": "Locks Requested"
    }
   ]
  },
  {
   "title": "InnoDB Main Thread Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_server_innodb_log_flush_usec_total{instance=\"$host\"}[$interval])/1000000 or irate(mysql_info_schema_innodb_metrics_server_innodb_log_flush_usec_total{instance=\"$host\"}[5m])/1000000",
     "legendFormat": "Log Flushing"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_server_innodb_ibuf_merge_usec_total{instance=\"$host\"}[$interval])/1000000 or irate(mysql_info_schema_innodb_metrics_server_innodb_ibuf_merge_usec_total{instance=\"$host\"}[5m])/1000000",
     "legendFormat": "Insert Buffer Merging"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_server_innodb_checkpoint_usec_total{instance=\"$host\"}[$interval])/1000000 or irate(mysql_info_schema_innodb_metrics_server_innodb_checkpoint_usec_total{instance=\"$host\"}[5m])/1000000",
     "legendFormat": "Checkpointing"
    }
   ]
  },
  {
   "title": "InnoDB Transactions Information",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_transaction_trx_rw_commits_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_rw_commits_total{instance=\"$host\"}[5m])",
     "legendFormat": "RW Transacton Commits "
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_transaction_trx_rollbacks_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_rollbacks_total{instance=\"$host\"}[5m])",
     "legendFormat": "Transaction Rollbacks"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_transaction_trx_ro_commits_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_ro_commits_total{instance=\"$host\"}[5m])",
     "legendFormat": "RO Transaction Commits"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_transaction_trx_nl_ro_commits_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_nl_ro_commits_total{instance=\"$host\"}[5m])",
     "legendFormat": "Non Locking RO Transaction Commits"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_transaction_trx_commits_insert_update_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_commits_insert_update_total{instance=\"$host\"}[5m])",
     "legendFormat": "Insert-Update Transaction Commits"
    },
    {
     "expr": "rate(mysql_global_status_innodb_max_trx_id{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_max_trx_id{instance=\"$host\"}[5m])",
     "legendFormat": "Transaction IDs Assigned"
    }
   ]
  },
  {
   "title": "InnoDB Undo Space Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_innodb_metrics_transaction_trx_rseg_current_size{instance=\"$host\"}*mysql_global_status_innodb_page_size{instance=\"$host\"}",
     "legendFormat": "Innodb Undo Space Used "
    }
   ]
  },
  {
   "title": "InnoDB Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_server_innodb_activity_count_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_activity_count_total{instance=\"$host\"}[5m])",
     "legendFormat": "InnoDB Activity"
    }
   ]
  },
  {
   "title": "InnoDB Contention - OS Waits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_os_waits_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_os_waits_total{instance=\"$host\"}[5m])",
     "legendFormat": "RW Locks S OS Waits"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_os_waits_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_os_waits_total{instance=\"$host\"}[5m])",
     "legendFormat": "RW Locks SX OS Waits"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_os_waits_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_os_waits_total{instance=\"$host\"}[5m])",
     "legendFormat": "RW Locks X OS Waits"
    }
   ]
  },
  {
   "title": "InnoDB Contention - Spin Rounds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_spin_rounds_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_spin_rounds_total{instance=\"$host\"}[5m])",
     "legendFormat": "RW Locks S Spin Rounds"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_spin_rounds_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_spin_rounds_total{instance=\"$host\"}[5m])",
     "legendFormat": "RW Locks SX Spin Rounds"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_spin_rounds_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_spin_rounds_total{instance=\"$host\"}[5m])",
     "legendFormat": "RW Locks X Spin Rounds"
    }
   ]
  },
  {
   "title": "InnoDB Group Commit Batch Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_transaction_trx_rw_commits_total{instance=\"$host\"}[$interval])/rate(mysql_global_status_innodb_log_writes{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_rw_commits_total{instance=\"$host\"}[5m])/irate(mysql_global_status_innodb_log_writes{instance=\"$host\"}[5m])",
     "legendFormat": "Group Commit Batch Size"
    }
   ]
  },
  {
   "title": "InnoDB Purge Throttling",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_innodb_metrics_purge_purge_dml_delay_usec{instance=\"$host\"}",
     "legendFormat": "Current Purge Delay"
    },
    {
     "expr": "mysql_global_variables_innodb_max_purge_lag_delay{instance=\"$host\"}",
     "legendFormat": "Max Purge Delay"
    }
   ]
  },
  {
   "title": "InnoDB AHI Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{instance=\"$host\"}[5m])",
     "legendFormat": "AHI - Searches"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=\"$host\"}[5m])",
     "legendFormat": "AHI - Hits"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=\"$host\"}[$interval])/rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=\"$host\"}[$interval])/rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{instance=\"$host\"}[5m])",
     "legendFormat": "AHI - Hit Ratio"
    }
   ]
  },
  {
   "title": "InnoDB AHI Maintenance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_added_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_added_total{instance=\"$host\"}[5m])",
     "legendFormat": "AHI - Pages Added"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_removed_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_removed_total{instance=\"$host\"}[5m])",
     "legendFormat": "AHI - Pages Removed"
    },
    {
     "expr": "rate( mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_added_total{instance=\"$host\"}[$interval]) or irate( mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_added_total{instance=\"$host\"}[5m])",
     "legendFormat": "AHI - Rows Added"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_removed_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_removed_total{instance=\"$host\"}[5m])",
     "legendFormat": "AHI - Rows Removed"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_updated_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_updated_total{instance=\"$host\"}[5m])",
     "legendFormat": "AHI - Rows Updated"
    }
   ]
  }
 ]
}