{
 "title": "MySQL: Performance Schema",
 "tags": [ "MySQL" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{bosh_job_name=\"mysql\"}, bosh_deployment)"
   },
   {
    "name": "galeranode",
    "label": "Galera-node",
    "query": "label_values(bosh_job_healthy{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"mysql\"}, bosh_job_ip)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up{instance=~\"$galeranode:.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance Schema File IO (Events)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(mysql_perf_schema_file_events_total{instance=\"$host\"}[$interval])>0) or topk(10, irate(mysql_perf_schema_file_events_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "{{event_name}} {{mode}}"
    }
   ]
  },
  {
   "title": "Performance Schema File IO (Load)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(mysql_perf_schema_file_events_seconds_total{instance=\"$host\"}[$interval])>0) or topk(10, irate(mysql_perf_schema_file_events_seconds_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "{{event_name}} {{mode}}"
    }
   ]
  },
  {
   "title": "Performance Schema File IO (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(mysql_perf_schema_file_events_bytes_total{instance=\"$host\"}[$interval])>0) or topk(10, irate(mysql_perf_schema_file_events_bytes_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "{{event_name}} {{mode}}"
    }
   ]
  },
  {
   "title": "Performance Schema Waits (Events)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(mysql_perf_schema_events_waits_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_perf_schema_events_waits_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "{{event_name}} "
    }
   ]
  },
  {
   "title": "Performance Schema Waits (Load)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\",event_name!='idle',event_name!='wait/io/table/sql/handler'}[$interval])>0) or topk(5, irate(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\",event_name!='idle',event_name!='wait/io/table/sql/handler'}[5m])>0)",
     "legendFormat": "{{event_name}} "
    }
   ]
  },
  {
   "title": "Index Access Operations (Load)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(mysql_perf_schema_index_io_waits_seconds_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_perf_schema_index_io_waits_seconds_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "{{operation}} {{index}} {{schema}}.{{name}}"
    }
   ]
  },
  {
   "title": "Table Access Operations (Load)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(mysql_perf_schema_table_io_waits_seconds_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_perf_schema_table_io_waits_seconds_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "{{operation}} {{schema}}.{{name}}"
    }
   ]
  }
 ]
}