{
 "title": "Prometheus: Targets",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Targets",
   "type": "singlestat",
   "description": "Total number of targets",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Targets Down",
   "type": "singlestat",
   "description": "Total number of targets down",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(up == 0)" }
   ]
  },
  {
   "title": "Samples Duplicated",
   "type": "singlestat",
   "description": "Total number of samples rejected due to duplicate timestamps but different values",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total)"
    }
   ]
  },
  {
   "title": "Sample Out of Bounds",
   "type": "singlestat",
   "description": "Total number of samples rejected due to timestamp falling outside of the time bounds",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total)"
    }
   ]
  },
  {
   "title": "Samples Out of Order",
   "type": "singlestat",
   "description": "Total number of samples rejected due to not being out of the expected order",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total)"
    }
   ]
  },
  {
   "title": "Samples Exceeded Limit",
   "type": "singlestat",
   "description": "Total number of scrapes that hit the sample limit and were rejected",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total)"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "graph",
   "description": "Number of targets per job",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(up) by(job)", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Samples Scraped",
   "type": "graph",
   "description": "Number of samples scraped",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped) by(job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Post Metric Relabelling",
   "type": "graph",
   "description": "Number of samples relabeled post metric",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scrape_samples_post_metric_relabeling) by(job)",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}