{
 "title": "Prometheus: Summary",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Targets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Targets Down",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(up == 0)" }
   ]
  },
  {
   "title": "Skipped Scrapes",
   "type": "singlestat",
   "description": "Total number of scrapes that were skipped because the metric storage was throttled",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prometheus_target_skipped_scrapes_total)"
    }
   ]
  },
  {
   "title": "Exceeded Sample Limit",
   "type": "singlestat",
   "description": "Total number of scrapes that hit the sample limit and were rejected",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total)"
    }
   ]
  },
  {
   "title": "Notifications Sent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_notifications_sent_total)"
    }
   ]
  },
  {
   "title": "Notifications Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_notifications_errors_total)"
    }
   ]
  },
  {
   "title": "Notifications Dropped",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_notifications_dropped_total)"
    }
   ]
  },
  {
   "title": "Notifications Queue Length",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_notifications_queue_length)"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(up) by(job)", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Samples Scraped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped) by(job)",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}