{
 "title": "CF: Doppler Server",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_counter_event_doppler_server_listeners_total_received_message_count_total, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_counter_event_doppler_server_listeners_total_received_message_count_total{environment=~\"$environment\"}, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sinks",
   "type": "graph",
   "description": "Instantaneous number of sinks known to the SinkManager. Emitted every 5 seconds.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_doppler_server_message_router_number_of_container_metric_sinks{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Container Metric"
    },
    {
     "expr": "sum(avg(firehose_value_metric_doppler_server_message_router_number_of_dump_sinks{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Dump"
    },
    {
     "expr": "sum(avg(firehose_value_metric_doppler_server_message_router_number_of_firehose_sinks{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Firehose"
    },
    {
     "expr": "sum(avg(firehose_value_metric_doppler_server_message_router_number_of_syslog_sinks{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Syslog"
    },
    {
     "expr": "sum(avg(firehose_value_metric_doppler_server_message_router_number_of_websocket_sinks{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Websocket"
    }
   ]
  },
  {
   "title": "Messages Unmarshalled",
   "type": "graph",
   "description": "Cumulative number of messages unmarshalled.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_dropsonde_unmarshaller_container_metric_received_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Container Metric"
    },
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_dropsonde_unmarshaller_counter_event_received_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Counter Event"
    },
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_dropsonde_unmarshaller_http_start_stop_received_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "HttpStartStop"
    },
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_dropsonde_unmarshaller_log_message_total_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Log Message"
    },
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_dropsonde_unmarshaller_value_metric_received_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Value Metric"
    },
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_dropsonde_unmarshaller_error_received_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Messages Received by Listeners",
   "type": "graph",
   "description": "Cumulative number of messages received across all of Doppler listeners (UDP, TCP, TLS).",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_listeners_total_received_message_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Bytes Received by Listeners",
   "type": "graph",
   "description": "Cumulative number of  bytes received across all of Doppler listeners (UDP, TCP, TLS).",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_listeners_total_received_byte_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Unmarshal Errors",
   "type": "graph",
   "description": "Number of errors when unmarshalling messages.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_dropsonde_unmarshaller_unmarshal_errors{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "graph",
   "description": "Total number of messages intentionally dropped by Doppler from all of its sinks due to back pressure. Emitted every 5 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_truncating_buffer_total_dropped_messages{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Messages"
    },
    {
     "expr": "sum(avg(firehose_counter_event_doppler_server_doppler_shed_envelopes_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Messages"
    }
   ]
  }
 ]
}