meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: alertmanager
    templates:
      - name: alertmanager
        release: prometheus
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z1
    networks: (( param "please set alertmanager networks" ))
    properties:
      alertmanager:
        route:
          receiver: default-receiver
        receivers:
          - name: default-receiver

  - name: prometheus
    templates:
      - name: bosh_alerts
        release: prometheus
      - name: cloudfoundry_alerts
        release: prometheus
      - name: kubernetes_alerts
        release: prometheus
      - name: mysql_alerts
        release: prometheus
      - name: p_rabbitmq_alerts
        release: prometheus
      - name: p_redis_alerts
        release: prometheus
      - name: probe_alerts
        release: prometheus
      - name: prometheus_alerts
        release: prometheus
      - name: rabbitmq_alerts
        release: prometheus
      - name: redis_alerts
        release: prometheus
      - name: prometheus
        release: prometheus
      - name: pushgateway
        release: prometheus
      - name: blackbox_exporter
        release: prometheus
      #- name: bosh_exporter
      #  release: prometheus
      #- name: bosh_tsdb_exporter
      #  release: prometheus
      #- name: cadvisor
      #  release: prometheus
      #- name: cf_exporter
      #  release: prometheus
      #- name: collectd_exporter
      #  release: prometheus
      #- name: consul_exporter
      #  release: prometheus
      #- name: elasticsearch_exporter
      #  release: prometheus
      #- name: firehose_exporter
      #  release: prometheus
      #- name: github_exporter
      #  release: prometheus
      #- name: graphite_exporter
      #  release: prometheus
      #- name: haproxy_exporter
      #  release: prometheus
      #- name: kube_state_metrics_exporter
      #  release: prometheus
      #- name: memcached_exporter
      #  release: prometheus
      #- name: mongodb_exporter
      #  release: prometheus
      #- name: mysqld_exporter
      #  release: prometheus
      #- name: nats_exporter
      #  release: prometheus
      #- name: postgres_exporter
      #  release: prometheus
      #- name: rabbitmq_exporter
      #  release: prometheus
      #- name: redis_exporter
      #  release: prometheus
      #- name: shield_exporter
      #  release: prometheus
      #- name: statsd_exporter
      #  release: prometheus
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z1
    networks: (( param "please set prometheus networks" ))
    properties:
      blackbox_exporter:
       config:
         modules:
           http_2xx:
             prober: http
             timeout: 5s

      prometheus:
        rule_files:
          - /var/vcap/packages/bosh_alerts/*.alerts
          - /var/vcap/packages/cloudfoundry_alerts/*.alerts
          - /var/vcap/packages/kubernetes_alerts/*.alerts
          - /var/vcap/packages/mysql_alerts/*.alerts
          - /var/vcap/packages/p_rabbitmq_alerts/*.alerts
          - /var/vcap/packages/p_redis_alerts/*.alerts
          - /var/vcap/packages/probe_alerts/*.alerts
          - /var/vcap/packages/prometheus_alerts/*.alerts
          - /var/vcap/packages/rabbitmq_alerts/*.alerts
          - /var/vcap/packages/redis_alerts/*.alerts
        scrape_configs:
          - job_name: blackbox
            metrics_path: /probe
            params:
              module:
                - http_2xx
            static_configs:
              - targets:
                - prometheus.io
            relabel_configs:
              - source_labels: [__address__]
                regex: (.*)(:80)?
                target_label: __param_target
                replacement: ${1}
              - source_labels: [__param_target]
                regex: (.*)
                target_label: instance
                replacement: ${1}
              - source_labels: []
                regex: .*
                target_label: __address__
                replacement: localhost:9115
          - job_name: bosh
            scrape_interval: 1m
            scrape_timeout: 1m
            static_configs:
              - targets:
                - localhost:9190
          - job_name: bosh_tsdb
            static_configs:
              - targets:
                - localhost:9194
          - job_name: cf
            static_configs:
              - targets:
                - localhost:9193
          - job_name: collectd
            static_configs:
              - targets:
                - localhost:9103
          - job_name: consul
            static_configs:
              - targets:
                - localhost:9107
          - job_name: elasticsearch
            static_configs:
              - targets:
                - localhost:9114
          - job_name: firehose
            static_configs:
              - targets:
                - localhost:9186
          - job_name: github
            static_configs:
              - targets:
                - localhost:9171
          - job_name: graphite
            static_configs:
              - targets:
                - localhost:9108
          - job_name: haproxy
            static_configs:
              - targets:
                - localhost:9101
          - job_name: kube_state_metrics_exporter
            static_configs:
              - targets:
                - localhost:9188
          - job_name: memcached_exporter
            static_configs:
              - targets:
                - localhost:9150
          - job_name: mysql
            static_configs:
              - targets:
                - localhost:9104
          - job_name: nats
            static_configs:
              - targets:
                - localhost:9118
          - job_name: node
            static_configs:
              - targets:
                - localhost:9100
          - job_name: postgres_exporter
            static_configs:
              - targets:
                - localhost:9113
          - job_name: prometheus
            static_configs:
              - targets:
                - localhost:9090
          - job_name: pushgateway
            static_configs:
              - targets:
                - localhost:9091
          - job_name: rabbitmq
            static_configs:
              - targets:
                - localhost:9125
          - job_name: redis
            static_configs:
              - targets:
                - localhost:9121
          - job_name: shield
            static_configs:
              - targets:
                - localhost:9179
          - job_name: statsd
            static_configs:
              - targets:
                - localhost:9102

  - name: grafana
    templates:
      - name: grafana
        release: prometheus
      - name: bosh_dashboards
        release: prometheus
      - name: cloudfoundry_dashboards
        release: prometheus
      - name: kubernetes_dashboards
        release: prometheus
      - name: mysql_dashboards
        release: prometheus
      - name: p_rabbitmq_dashboards
        release: prometheus
      - name: p_redis_dashboards
        release: prometheus
      - name: probe_dashboards
        release: prometheus
      - name: prometheus_dashboards
        release: prometheus
      - name: rabbitmq_dashboards
        release: prometheus
      - name: redis_dashboards
        release: prometheus
      - name: system_dashboards
        release: prometheus
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z1
    networks: (( param "please set grafana networks" ))
    properties:
      grafana:
        security:
          admin_password: admin
      dashboards:
        json:
          enabled: true
      prometheus:
        dashboard_files:
          - /var/vcap/packages/bosh_dashboards/*.json
          - /var/vcap/packages/cloudfoundry_dashboards/*.json
          - /var/vcap/packages/kubernetes_dashboards/*.json
          - /var/vcap/packages/mysql_dashboards/*.json
          - /var/vcap/packages/p_rabbitmq_dashboards/*.json
          - /var/vcap/packages/p_redis_dashboards/*.json
          - /var/vcap/packages/probe_dashboards/*.json
          - /var/vcap/packages/prometheus_dashboards/*.json
          - /var/vcap/packages/rabbitmq_dashboards/*.json
          - /var/vcap/packages/redis_dashboardss/*.json
          - /var/vcap/packages/system_dashboards/*.json

  - name: nginx
    templates:
      - name: nginx
        release: prometheus
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z1
    networks: (( param "please set nginx networks" ))
    properties:
      nginx:
        alertmanager:
          auth_username: admin
          auth_password: admin
        prometheus:
          auth_username: admin
          auth_password: admin

networks: (( param "please set networks" ))

properties: {}
