{
 "title": "RabbitMQ: Queues",
 "tags": [ "RabbitMQ" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(rabbitmq_up, instance)"
   },
   {
    "name": "vhost",
    "label": "vHost",
    "query": "label_values(rabbitmq_queue_messages{instance=~\"$host\"}, vhost)"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values(rabbitmq_queue_messages{instance=~\"$host\",vhost=~\"$vhost\"}, queue)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rabbitmq_queue_consumers{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})"
    }
   ]
  },
  {
   "title": "Consumer Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rabbitmq_queue_consumer_utilisation{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rabbitmq_queue_messages{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})"
    }
   ]
  },
  {
   "title": "Queue Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rabbitmq_queue_memory{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})"
    }
   ]
  },
  {
   "title": "Queue Messages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rabbitmq_queue_messages_published_total{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Published"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_confirmed_total{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Confirmed"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_delivered_total{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Delivered"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_delivered_noack_total{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Delivered noack"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_get_total{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_get_noack_total{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Get noack"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_redelivered_total{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Redelivered"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_returned_total{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Queue Messages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rabbitmq_queue_messages_ready{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_unacknowledged{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Unacknowledged"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_ready_ram{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Ready In Memory"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_unacknowledged_ram{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Unacknowledged In Memory"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_ram{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "In Memory"
    },
    {
     "expr": "avg(rabbitmq_queue_messages_redelivered_total{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Redelivered"
    }
   ]
  },
  {
   "title": "Message Body Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(rabbitmq_queue_message_bytes_ready{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "avg(rabbitmq_queue_message_bytes_unacknowledged{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Unacknowledged"
    },
    {
     "expr": "avg(rabbitmq_queue_message_bytes_ram{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "RAM"
    },
    {
     "expr": "avg(rabbitmq_queue_message_bytes_persistent{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Persistent"
    }
   ]
  },
  {
   "title": "Disk Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rabbitmq_queue_disk_reads{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Reads"
    },
    {
     "expr": "avg(rabbitmq_queue_disk_writes{instance=~\"$host\",vhost=~\"$vhost\",queue=\"$queue\"})",
     "legendFormat": "Writes"
    }
   ]
  }
 ]
}