{
 "title": "Kubernetes: Rest Client",
 "tags": [
  "kubernetes",
  "rest"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(rest_client_requests_total, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rest_client_requests_total{job=~\"$job\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Requests by Code",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rest_client_requests_total{job=~\"$job\"}) by(code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Requests by Verb",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rest_client_requests_total{job=~\"$job\"}) by(method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rest_client_request_latency_seconds_sum{job=~\"$job\"} / rest_client_request_latency_seconds_count{job=~\"$job\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency by Verb",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rest_client_request_latency_seconds_sum{job=~\"$job\"} / rest_client_request_latency_seconds_count{job=~\"$job\"}) by(verb)",
     "legendFormat": "{{ verb }}"
    }
   ]
  }
 ]
}