{
 "title": "Kubernetes: Admission Quota Controller",
 "tags": [
  "kubernetes",
  "apiserver"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Workqueue Adds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(admission_quota_controller_adds)",
     "legendFormat": "Workqueue Adds"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(admission_quota_controller_depth)",
     "legendFormat": "Workqueue Depth"
    }
   ]
  },
  {
   "title": "Queue Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(admission_quota_controller_queue_latency_sum / admission_quota_controller_queue_latency_count)",
     "legendFormat": "Queue Latency"
    }
   ]
  },
  {
   "title": "Work Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(admission_quota_controller_work_duration_sum / admission_quota_controller_work_duration_count)",
     "legendFormat": "Work Duration"
    }
   ]
  }
 ]
}