{
 "title": "Kubernetes: DaemonSets",
 "tags": [
  "kubernetes",
  "daemonsets"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_daemonset_metadata_generation, namespace)"
   },
   {
    "name": "daemonset",
    "label": "DaemonSet",
    "query": "label_values(kube_daemonset_metadata_generation{namespace=~\"$namespace\"}, daemonset)"
   }
  ]
 },
 "panels": [
  {
   "title": "Created",
   "type": "singlestat",
   "description": "When the daemonset was created",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(kube_daemonset_created{namespace=~\"$namespace\",daemonset=~\"$daemonset\"})"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "description": "Sequence number representing a specific generation of the desired state",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_daemonset_metadata_generation{namespace=~\"$namespace\",daemonset=~\"$daemonset\"})  "
    }
   ]
  },
  {
   "title": "Scheduling",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_daemonset_status_desired_number_scheduled{namespace=~\"$namespace\",daemonset=~\"$daemonset\"}) by(namespace, daemonset)",
     "legendFormat": "Desired"
    },
    {
     "expr": "avg(kube_daemonset_status_current_number_scheduled{namespace=~\"$namespace\",daemonset=~\"$daemonset\"}) by(namespace, daemonset)",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "avg(kube_daemonset_status_number_misscheduled{namespace=~\"$namespace\",daemonset=~\"$daemonset\"}) by(namespace, daemonset)",
     "legendFormat": "Misscheduled"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_daemonset_status_number_available{namespace=~\"$namespace\",daemonset=~\"$daemonset\"}) by(namespace, daemonset)",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(kube_daemonset_status_number_unavailable{namespace=~\"$namespace\",daemonset=~\"$daemonset\"}) by(namespace, daemonset)",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "avg(kube_daemonset_status_number_ready{namespace=~\"$namespace\",daemonset=~\"$daemonset\"}) by(namespace, daemonset)",
     "legendFormat": "Ready"
    }
   ]
  }
 ]
}