{
 "title": "Kubernetes: Pods",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Created",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(kube_pod_created{namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Started",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(kube_pod_start_time{namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Created By",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"}) by(created_by_kind, created_by_name)",
     "legendFormat": "{{ created_by_kind  }} / {{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Host IP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"}) by(host_ip)",
     "legendFormat": "{{ host_ip }}"
    }
   ]
  },
  {
   "title": "Pod IP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"}) by(pod_ip)",
     "legendFormat": "{{ pod_ip }}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"}) by(node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Phase",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Ready Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_ready{namespace=~\"$namespace\",pod=~\"$pod\",condition=\"true\"}) by(namespace, pod, condition)) by(condition)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(avg(kube_pod_status_ready{namespace=~\"$namespace\",pod=~\"$pod\",condition=\"false\"}) by(namespace, pod, condition)) by(condition)",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "sum(avg(kube_pod_status_ready{namespace=~\"$namespace\",pod=~\"$pod\",condition=\"unknown\"}) by(namespace, pod, condition)) by(condition)",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Schedule Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_scheduled{namespace=~\"$namespace\",pod=~\"$pod\",condition=\"true\"}) by(namespace, pod, condition)) by(condition)",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(avg(kube_pod_status_scheduled{namespace=~\"$namespace\",pod=~\"$pod\",condition=\"false\"}) by(namespace, pod, condition)) by(condition)",
     "legendFormat": "Not Scheduled"
    },
    {
     "expr": "sum(avg(kube_pod_status_scheduled{namespace=~\"$namespace\",pod=~\"$pod\",condition=\"unknown\"}) by(namespace, pod, condition)) by(condition)",
     "legendFormat": "Unknown"
    }
   ]
  }
 ]
}