{
 "title": "Apps: System v2",
 "tags": [
  "apps",
  "v2"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(cf_application_info, deployment)"
   },
   {
    "name": "cf_organization_name",
    "label": "Organization",
    "query": "label_values(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}, organization_name)"
   },
   {
    "name": "cf_space_name",
    "label": "Space",
    "query": "label_values(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\"}, space_name)"
   },
   {
    "name": "cf_application_name",
    "label": "Application",
    "query": "label_values(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\", space_name=~\"$cf_space_name\"}, application_name)"
   },
   {
    "name": "cf_application_id",
    "label": "Application ID",
    "query": "label_values(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\", space_name=~\"$cf_space_name\",application_name=~\"$cf_application_name\"}, application_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "singlestat",
   "description": "Application State",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"}) by(state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Diego Cell IP addresses",
   "type": "table-old",
   "description": "Show the IP address of the Diego Cell where the Application Instance is running.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(firehose_container_metric_cpu_percentage{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"}) by(instance_index,  bosh_job_ip)",
     "legendFormat": "{{ instance_index }}: {{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Number of Application Instances",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(cf_application_instances{deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Desired"
    },
    {
     "expr": "min(cf_application_instances_running{deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average Application % CPU Usage.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_cpu_percentage{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage by Application Instance",
   "type": "graph",
   "description": "CPU Usage by Application Instance.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_cpu_percentage{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"}) by(instance_index) ",
     "legendFormat": "{{ instance_index }}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Average Application Memory Usage.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_memory_bytes{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(firehose_container_metric_memory_bytes_quota{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Memory Usage by Application Instance",
   "type": "graph",
   "description": "Memory Usage by Application Instance",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_memory_bytes{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"}) by(instance_index) ",
     "legendFormat": "{{ instance_index }}"
    },
    {
     "expr": "avg(firehose_container_metric_memory_bytes_quota{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Average Disk Allocated",
   "type": "graph",
   "description": "Average Application Disk Allocated.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_disk_bytes{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(firehose_container_metric_disk_bytes_quota{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Allocated Disk Space  by Application Instance",
   "type": "graph",
   "description": "Allocated Disk Space  by Application Instance.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_disk_bytes{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"}) by(instance_index) ",
     "legendFormat": "{{ instance_index }}"
    },
    {
     "expr": "avg(firehose_container_metric_disk_bytes_quota{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Quota"
    }
   ]
  }
 ]
}