{
 "title": "Apps: Requests",
 "tags": [ "apps" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(cf_application_info, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(cf_application_info{environment=~\"$environment\"}, deployment)"
   },
   {
    "name": "cf_organization_name",
    "label": "Organization",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\"}, organization_name)"
   },
   {
    "name": "cf_space_name",
    "label": "Space",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\"}, space_name)"
   },
   {
    "name": "cf_application_name",
    "label": "Application",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\", space_name=~\"$cf_space_name\"}, application_name)"
   },
   {
    "name": "cf_application_id",
    "label": "Application ID",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\", space_name=~\"$cf_space_name\",application_name=~\"$cf_application_name\"}, application_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rate Requests per second",
   "type": "graph",
   "description": "Requests per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[10m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "description": "Number of requests.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Rate Requests by Application Instance per second",
   "type": "graph",
   "description": "Requests per application instance per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[10m])) by(instance_id)",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Total Requests by Application Instance",
   "type": "graph",
   "description": "Number of requests per application instance.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}) by(instance_id)",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Rate Requests by Method per second",
   "type": "graph",
   "description": "Requests by method per second during the last 5 mintes.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[10m])) by(method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Total Requests by Method",
   "type": "graph",
   "description": "Number of requests by method.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}) by(method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Rate Requests by Status Code per second",
   "type": "graph",
   "description": "Requests by status code per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[10m])) by(status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Total Requests by Status Code",
   "type": "graph",
   "description": "Number of requests by status code.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}) by(status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Rate Requests by Scheme per second",
   "type": "graph",
   "description": "Requests by scheme per second during the last 5 mintes.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[10m])) by(scheme)",
     "legendFormat": "{{ scheme }}"
    }
   ]
  },
  {
   "title": "Total Requests by Scheme",
   "type": "graph",
   "description": "Number of requests by scheme.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}) by(scheme)",
     "legendFormat": "{{ scheme }}"
    }
   ]
  },
  {
   "title": "Rate Requests by Host per second",
   "type": "graph",
   "description": "Requests by host per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[10m])) by(host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Total Requests by Host",
   "type": "graph",
   "description": "Number of requests by host.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_http_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}) by(host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "graph",
   "description": "Response Size.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_http_response_size_bytes_sum{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"} / firehose_http_response_size_bytes_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Response Size (Quantiles)",
   "type": "graph",
   "description": "Response Size (Quantiles).",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_http_response_size_bytes{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}) by(quantile)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  }
 ]
}