{
 "title": "Apps: Latency",
 "tags": [ "apps" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(cf_application_info, environment)"
    }
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(cf_application_info{environment=~\"$environment\"}, deployment)"
    }
   },
   {
    "name": "cf_organization_name",
    "label": "Organization",
    "query": {
     "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\"}, organization_name)"
    }
   },
   {
    "name": "cf_space_name",
    "label": "Space",
    "query": {
     "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\"}, space_name)"
    }
   },
   {
    "name": "cf_application_name",
    "label": "Application",
    "query": {
     "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\", space_name=~\"$cf_space_name\"}, application_name)"
    }
   },
   {
    "name": "cf_application_id",
    "label": "Application ID",
    "query": {
     "query": "label_values(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\", space_name=~\"$cf_space_name\",application_name=~\"$cf_application_name\"}, application_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Application Latency.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(firehose_http_duration_seconds_sum{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]) / rate(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]))",
     "legendFormat": "Client"
    }
   ]
  },
  {
   "title": "App Response Time by Percent",
   "type": "timeseries",
   "description": "Percentage of requests processed in less than a given time for selected app",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(firehose_http_duration_seconds_bucket{le=\"0.005\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m])) by (le)  \n/ on()\nsum(rate(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]))\n* 100",
     "legendFormat": "5 ms"
    },
    {
     "expr": "sum(rate(firehose_http_duration_seconds_bucket{le=\"0.01\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m])) by (le)  \n/ on()\nsum(rate(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]))\n* 100",
     "legendFormat": "10 ms"
    },
    {
     "expr": "sum(rate(firehose_http_duration_seconds_bucket{le=\"0.1\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m])) by (le)  \n/ on()\nsum(rate(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]))\n* 100",
     "legendFormat": "100 ms"
    },
    {
     "expr": "sum(rate(firehose_http_duration_seconds_bucket{le=\"0.25\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m])) by (le)  \n/ on()\nsum(rate(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]))\n* 100",
     "legendFormat": "250 ms"
    },
    {
     "expr": "sum(rate(firehose_http_duration_seconds_bucket{le=\"0.5\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m])) by (le)  \n/ on()\nsum(rate(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]))\n* 100",
     "legendFormat": "500 ms"
    },
    {
     "expr": "sum(rate(firehose_http_duration_seconds_bucket{le=~\"1([.]0)?\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m])) by (le)  \n/ on()\nsum(rate(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]))\n* 100",
     "legendFormat": "1 s"
    },
    {
     "expr": "sum(rate(firehose_http_duration_seconds_bucket{le=\"2.5\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m])) by (le)  \n/ on()\nsum(rate(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]))\n* 100",
     "legendFormat": "2.5 s"
    },
    {
     "expr": "sum(rate(firehose_http_duration_seconds_bucket{le=~\"5([.]0)?\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m])) by (le)  \n/ on()\nsum(rate(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]))\n* 100",
     "legendFormat": "5 s"
    },
    {
     "expr": "sum(rate(firehose_http_duration_seconds_bucket{le=~\"10([.]0)?\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m])) by (le)  \n/ on()\nsum(rate(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[5m]))\n* 100",
     "legendFormat": "10 s"
    }
   ]
  },
  {
   "title": "App Global Response Time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(firehose_http_duration_seconds_bucket{environment=~\"$environment\",application_id=~\"$cf_application_id\"}[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Q.O.S.",
   "type": "timeseries",
   "description": "Percentage of requests processed in less than a given time for selected app",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(firehose_http_duration_seconds_bucket{le=\"0.005\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}) by (le)  \n/ on()\nsum(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"})\n* 100",
     "legendFormat": "5 ms"
    },
    {
     "expr": "sum(firehose_http_duration_seconds_bucket{le=\"0.01\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}) by (le)  \n/ on()\nsum(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"})\n* 100",
     "legendFormat": "10 ms"
    },
    {
     "expr": "sum(firehose_http_duration_seconds_bucket{le=\"0.1\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}) by (le)  \n/ on()\nsum(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"})\n* 100",
     "legendFormat": "100 ms"
    },
    {
     "expr": "sum(firehose_http_duration_seconds_bucket{le=\"0.25\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}) by (le)  \n/ on()\nsum(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"})\n* 100",
     "legendFormat": "250 ms"
    },
    {
     "expr": "sum(firehose_http_duration_seconds_bucket{le=\"0.5\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}) by (le)  \n/ on()\nsum(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"})\n* 100",
     "legendFormat": "500 ms"
    },
    {
     "expr": "sum(firehose_http_duration_seconds_bucket{le=~\"1([.]0)?\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}) by (le)  \n/ on()\nsum(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"})\n* 100",
     "legendFormat": "1 s"
    },
    {
     "expr": "sum(firehose_http_duration_seconds_bucket{le=\"2.5\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}) by (le)  \n/ on()\nsum(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"})\n* 100",
     "legendFormat": "2.5 s"
    },
    {
     "expr": "sum(firehose_http_duration_seconds_bucket{le=~\"5([.]0)?\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}) by (le)  \n/ on()\nsum(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"})\n* 100",
     "legendFormat": "5 s"
    },
    {
     "expr": "sum(firehose_http_duration_seconds_bucket{le=~\"10([.]0)?\", environment=~\"$environment\",application_id=~\"$cf_application_id\"}) by (le)  \n/ on()\nsum(firehose_http_duration_seconds_count{environment=~\"$environment\",application_id=~\"$cf_application_id\"})\n* 100",
     "legendFormat": "10 s"
    }
   ]
  }
 ]
}