{
 "title": "CF: Cell Summary v2",
 "tags": [
  "cf",
  "diego",
  "v2"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_value_metric_rep_capacity_total_containers, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(firehose_value_metric_rep_capacity_total_containers{bosh_deployment=~\"${bosh_deployment}\"}, bosh_job_name)"
   },
   {
    "name": "bosh_job_ip",
    "label": "IP",
    "query": "label_values(firehose_value_metric_rep_capacity_total_containers{bosh_deployment=~\"${bosh_deployment}\", bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cell Status",
   "type": "singlestat",
   "description": "Status of this Diego cell",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(firehose_value_metric_rep_garden_health_check_failed{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\", bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"})"
    }
   ]
  },
  {
   "title": "Remaining Containers",
   "type": "singlestat",
   "description": "Number of remaining containers in this Diego cell",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))"
    }
   ]
  },
  {
   "title": "Remaining Memory",
   "type": "singlestat",
   "description": "Remaining memory in this Diego cell",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))"
    }
   ]
  },
  {
   "title": "Remaining Disk",
   "type": "singlestat",
   "description": "Remaining disk in this Diego cell",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "graph",
   "description": "Cumulative used and available number of containers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_total_containers{bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)) - sum(avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Application Instances",
   "type": "table-old",
   "description": "Application instances running in this Diego cell",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "avg(firehose_container_metric_cpu_percentage{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(application_id, instance_index) * on(application_id) group_left(organization_name, space_name, application_name) min(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(organization_name, space_name, application_name,  application_id)",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ application_name }} #{{ instance_index }}"
    }
   ]
  },
  {
   "title": "Total Cell Memory",
   "type": "graph",
   "description": "Cumulative allocated and available MiB of memory to allocate to containers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_total_memory{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)) - sum(avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Current Memory Usage per Application Instance",
   "type": "table-old",
   "description": "Current memory usage per application instance running in this Diego cell.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "min(firehose_container_metric_memory_bytes{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(application_id, instance_index) * on(application_id) group_left(organization_name, space_name, application_name) min(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(organization_name, space_name, application_name,  application_id)",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ application_name }} #{{ instance_index }}"
    }
   ]
  },
  {
   "title": "Total Cell Disk",
   "type": "graph",
   "description": "Cumulative allocated and available MiB of disk to allocate to containers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_total_disk{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)) - sum(avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Current Disk Usage per Application Instance",
   "type": "table-old",
   "description": "Current disk usage per application instance running in this Diego cell.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "min(firehose_container_metric_disk_bytes{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\",bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\"}) by(application_id, instance_index) * on(application_id) group_left(organization_name, space_name, application_name) min(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(organization_name, space_name, application_name,  application_id)",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ application_name }} #{{ instance_index }}"
    }
   ]
  }
 ]
}