{
 "title": "CF: Cells Capacity",
 "tags": [
  "cf",
  "diego"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(firehose_value_metric_rep_capacity_total_containers, environment)"
    }
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(firehose_value_metric_rep_capacity_total_containers{environment=~\"$environment\"}, bosh_deployment)"
    }
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": {
     "query": "label_values(firehose_value_metric_rep_capacity_total_containers{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\"}, bosh_job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Cells",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(count(firehose_value_metric_rep_capacity_total_containers{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\"}) by(instance))"
    }
   ]
  },
  {
   "title": "Cell with Least Remaining Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\"}) by(instance))"
    }
   ]
  },
  {
   "title": "Cell with Least Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bottomk(1, min(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_ip))",
     "legendFormat": "{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Total Cell Memory",
   "type": "timeseries",
   "description": "Cumulative used and available MiB of memory to allocate to containers.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_total_memory{environment=~\"$environment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_name, bosh_job_ip)) - sum(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_name, bosh_job_ip))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_name, bosh_job_ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Total Cell Disk",
   "type": "timeseries",
   "description": "Cumulative used and available MiB of disk to allocate to containers.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_total_disk{environment=~\"$environment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_name, bosh_job_ip)) - sum(avg(firehose_value_metric_rep_capacity_remaining_disk{environment=~\"$environment\",bosh_job_name=~\"$bosh_job_name\"}) by( bosh_job_name, bosh_job_ip))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_disk{environment=~\"$environment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_name, bosh_job_ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Running Containers Per Cell",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_rep_capacity_total_containers{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\"} - firehose_value_metric_rep_capacity_remaining_containers{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_ip)",
     "legendFormat": "{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Memory Used Per Cell",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_rep_capacity_total_memory{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\"} - firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_ip)",
     "legendFormat": "{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Percent of CPU Used Per Cell",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bosh_job_process_cpu_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_ip)",
     "legendFormat": "{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Disk Used Per Cell",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_rep_capacity_total_disk{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\"} - firehose_value_metric_rep_capacity_remaining_disk{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_ip)",
     "legendFormat": "{{ bosh_job_ip }}"
    }
   ]
  }
 ]
}