{
 "title": "CF: Cloud Controller",
 "tags": [ "cf" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_value_metric_cc_job_queue_length_total, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_value_metric_cc_job_queue_length_total{environment=~\"$environment\"}, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Completed (5 min rate)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(firehose_value_metric_cc_requests_completed{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "description": "Cumulative number of HTTP response status codes. This resets when the Cloud Controller process is restarted and is incremented at the end of each request cycle. Emitted for each Cloud Controller request.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_cc_http_status_1_xx{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_http_status_2_xx{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_http_status_3_xx{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_http_status_4_xx{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_http_status_5_xx{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Job Queue Length",
   "type": "graph",
   "description": "Total number of background jobs in the queues that have yet to run for the first time. Emitted every 30 seconds per VM.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_cc_job_queue_length_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Failed jobs",
   "type": "graph",
   "description": "Number of failed jobs in all queues. By default, Cloud Controller deletes failed jobs after 31 days. Emitted every 30 seconds per VM.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_cc_failed_job_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Cumulative number of requests that have been processed and are currently being processed. Emitted for each Cloud Controller request.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_cc_requests_completed{environment=~\"$environment\",environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_requests_outstanding{environment=~\"$environment\",environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Outstanding"
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "graph",
   "description": "Cumulative number of log messages. The count resets when the Cloud Controller process is restarted. Emitted every 30 seconds per VM.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_cc_log_count_info{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "info"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_log_count_warn{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "warn"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_log_count_debug{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "debug"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_log_count_debug_1{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "debug1"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_log_count_debug_2{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "debug2"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_log_count_error{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_log_count_fatal{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "fatal"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_log_count_off{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "off"
    }
   ]
  },
  {
   "title": "Result Size",
   "type": "graph",
   "description": "Number of tasks in the result.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_cc_thread_info_event_machine_resultqueue_size{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) ) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_thread_info_event_machine_resultqueue_num_waiting{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) ) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "title": "Threadque Size",
   "type": "graph",
   "description": "Number of tasks in the threadqueue.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_cc_thread_info_event_machine_threadqueue_size{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) ) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(avg(firehose_value_metric_cc_thread_info_event_machine_threadqueue_num_waiting{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) ) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "Scheduled"
    }
   ]
  }
 ]
}