{
 "title": "CF: Diego Health v2",
 "tags": [
  "cf",
  "diego",
  "v2"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_value_metric_rep_garden_health_check_failed, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "CF Apps Synchronized",
   "type": "singlestat",
   "description": "Whether the cf-app domain is up-to-date, so that CF apps from CC have been synchronized with DesiredLRPs for Diego to run. Emitted every 30 seconds.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(firehose_value_metric_bbs_domain_cf_apps{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})"
    }
   ]
  },
  {
   "title": "CF Tasks Synchronized",
   "type": "singlestat",
   "description": "Whether the cf-tasksdomain is up-to-date, so that CF tasks from CC have been synchronized with tasks for Diego to run. Emitted every 30 seconds.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(firehose_value_metric_bbs_domain_cf_tasks{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Cells",
   "type": "graph",
   "description": "Whether the cell has failed to pass its healthcheck against the garden backend. 0 signifies healthy, and 1 signifies unhealthy. Emitted every 30 seconds.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_rep_garden_health_check_failed{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  }
 ]
}