{
 "title": "CF: Etcd",
 "tags": [
  "cf",
  "etcd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_value_metric_etcd_is_leader, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_value_metric_etcd_is_leader{environment=~\"$environment\"}, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(count(firehose_value_metric_etcd_is_leader{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"} == 1) by(instance, bosh_job_ip)) by(bosh_job_ip)",
     "legendFormat": "{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "stat",
   "description": "Number of etcd followers. Emitted every 30 seconds.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_etcd_followers{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_job_ip))"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_etcd_watchers{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Raft Term",
   "type": "timeseries",
   "description": "X-Raft-Term value from the /stats/store endpoint. Emitted every 30 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_etcd_raft_term{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Raft Index",
   "type": "timeseries",
   "description": "X-Raft-Index value from the /stats/store endpoint. Emitted every 30 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_etcd_raft_index{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Bandwidth Rate",
   "type": "timeseries",
   "description": "Number of bytes per second etcd leader is sending and etcd followers are receivinb. This value is undefined on single member clusters. Emitted every 30 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_etcd_receiving_bandwidth_rate{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "Receiving ({{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }})"
    },
    {
     "expr": "avg(firehose_value_metric_etcd_sending_bandwidth_rate{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "Sending ({{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Number of requests per second etcd leader is sending and etcd followers are receiving. This value is undefined on single member clusters. Emitted every 30 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_etcd_receiving_request_rate{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "Receiving ({{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }})"
    },
    {
     "expr": "avg(firehose_value_metric_etcd_sending_request_rate{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "Sending ({{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Current latency in milliseconds from leader to a specific follower. Emitted every 30 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_etcd_latency{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Append Requests Rate",
   "type": "timeseries",
   "description": "Number of append requests processed and sent. Emitted every 30 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(firehose_value_metric_etcd_received_append_requests{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "Received ({{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }})"
    },
    {
     "expr": "avg(rate(firehose_value_metric_etcd_sent_append_requests{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "Sent ({{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }})"
    }
   ]
  }
 ]
}