{
 "title": "CF: KPIs v2",
 "tags": [
  "cf",
  "v2"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_counter_event_gorouter_total_requests_total, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unhealthy Cells",
   "type": "singlestat",
   "description": "Whether the cell has failed to pass its healthcheck against the garden backend.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(min(firehose_value_metric_rep_garden_health_check_failed{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip) == 1)"
    }
   ]
  },
  {
   "title": "LRPs Missing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(firehose_value_metric_bbs_lr_ps_missing{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})"
    },
    { "expr": "lr_p" }
   ]
  },
  {
   "title": "CF Apps Synchronized",
   "type": "singlestat",
   "description": "Whether the cf-app domain is up-to-date, so that CF apps from CC have been synchronized with DesiredLRPs for Diego to run.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(firehose_value_metric_bbs_domain_cf_apps{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})"
    }
   ]
  },
  {
   "title": "CF Tasks Synchronized",
   "type": "singlestat",
   "description": "Whether the cf-tasks domain is up-to-date, so that CF tasks from CC have been synchronized with tasks for Diego to run.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(firehose_value_metric_bbs_domain_cf_tasks{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})"
    }
   ]
  },
  {
   "title": "Slow Consumer Alert",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(firehose_slow_consumer_alert)"
    }
   ]
  },
  {
   "title": "Avg LRPs 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(firehose_value_metric_bbs_lr_ps_running{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[1d]))"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "singlestat",
   "description": "Number of routes registered.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_gorouter_total_routes{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})",
     "legendFormat": "Routes"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "description": "Available MiB of memory to allocate to containers.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "min(avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Least Available Memory"
    },
    {
     "expr": "max(avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Most Available Memory"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Total Available Available Memory"
    }
   ]
  },
  {
   "title": "Available Disk",
   "type": "graph",
   "description": "Available MiB of disk to allocate to containers.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "min(avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Least Available Disk"
    },
    {
     "expr": "max(avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Most Available Disk"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Total Available Disk"
    }
   ]
  },
  {
   "title": "Available Containers",
   "type": "graph",
   "description": "Available number of containers.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_deployment=~\"${bosh_deployment}\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Least Available Containers"
    },
    {
     "expr": "max(avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_deployment=~\"${bosh_deployment}\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Most Available Containers"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_deployment=~\"${bosh_deployment}\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Total Available Containers"
    }
   ]
  },
  {
   "title": "BBS Requests per Second (max)",
   "type": "graph",
   "description": "Max number of requests per second received by the BBS.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_bbs_request_count_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m]))",
     "legendFormat": "Req/Sec"
    }
   ]
  },
  {
   "title": "BBS Request Latency (max)",
   "type": "graph",
   "description": "Max time in nanoseconds that the BBS took to handle requests to its API endpoints.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_bbs_request_latency{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "BBS Convergence Duration (max)",
   "type": "graph",
   "description": "Max time in nanoseconds that the BBS took to run its LRP and Task convergence pass. Emitted when LRP and Task convergence runs.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_bbs_convergence_lrp_duration{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})",
     "legendFormat": "LRPs"
    },
    {
     "expr": "max(firehose_value_metric_bbs_convergence_task_duration{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Router Requests per Second (max)",
   "type": "graph",
   "description": "Max number of requests per second received by the Gorouter.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_gorouter_total_requests_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m]))",
     "legendFormat": "Req/Sec"
    }
   ]
  },
  {
   "title": "Router Latency (max)",
   "type": "graph",
   "description": "Max time in nanoseconds that the Gorouter took to handle requests to its application endpoints.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_gorouter_latency{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Router Bad Gateway Responses per Second (max)",
   "type": "graph",
   "description": "Max number of Gorouter's HTTP Bad Gateway responses per second.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_gorouter_bad_gateways_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m]))",
     "legendFormat": "Resp/sec"
    }
   ]
  },
  {
   "title": "CC Requests Completed per Second (max)",
   "type": "graph",
   "description": "Max number of requests per second received by the Cloud Controller.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_value_metric_cc_requests_completed{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m]))",
     "legendFormat": "Req/sec"
    }
   ]
  },
  {
   "title": "LRPs Velocity (max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_value_metric_bbs_lr_ps_desired{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[30m]))",
     "legendFormat": "LRPs Desired"
    },
    {
     "expr": "max(rate(firehose_value_metric_bbs_lr_ps_running{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[30m]))",
     "legendFormat": "LRPs Running"
    }
   ]
  },
  {
   "title": "Router 5xx Responses per Second (max)",
   "type": "graph",
   "description": "Max number of GoRouter's HTTP 5xx responses per second.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_gorouter_responses_5_xx_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m]))",
     "legendFormat": "5xx resp/sec"
    }
   ]
  }
 ]
}