{
 "title": "CF: KPIs",
 "tags": [ "cf" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_counter_event_gorouter_total_requests_total, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_counter_event_gorouter_total_requests_total{environment=~\"$environment\"}, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unhealthy Cells",
   "type": "singlestat",
   "description": "Whether the cell has failed to pass its healthcheck against the garden backend.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(min(firehose_value_metric_rep_garden_health_check_failed{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip) == 1)"
    }
   ]
  },
  {
   "title": "LRPs Missing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(firehose_value_metric_bbs_lr_ps_missing{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})"
    }
   ]
  },
  {
   "title": "CF Apps Synchronized",
   "type": "singlestat",
   "description": "Whether the cf-app domain is up-to-date, so that CF apps from CC have been synchronized with DesiredLRPs for Diego to run.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(firehose_value_metric_bbs_domain_cf_apps{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})"
    }
   ]
  },
  {
   "title": "CF Tasks Synchronized",
   "type": "singlestat",
   "description": "Whether the cf-tasks domain is up-to-date, so that CF tasks from CC have been synchronized with tasks for Diego to run.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(firehose_value_metric_bbs_domain_cf_tasks{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})"
    }
   ]
  },
  {
   "title": "Slow Consumer Alert",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(firehose_slow_consumer_alert{environment=~\"$environment\"})"
    }
   ]
  },
  {
   "title": "Consul Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(firehose_value_metric_route_emitter_consul_down_mode{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})"
    }
   ]
  },
  {
   "title": "Avg LRPs 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(firehose_value_metric_bbs_lr_ps_running{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[1d]))"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "singlestat",
   "description": "Number of routes registered.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_gorouter_total_routes{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})",
     "legendFormat": "Routes"
    }
   ]
  },
  {
   "title": "Failed User Authentications",
   "type": "singlestat",
   "description": "Number of failed user authentication attempts since the last startup.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_uaa_audit_service_user_authentication_failure_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "description": "Available MiB of memory to allocate to containers.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "min(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Least Available Memory"
    },
    {
     "expr": "max(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Most Available Memory"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Total Available Available Memory"
    }
   ]
  },
  {
   "title": "Available Disk",
   "type": "graph",
   "description": "Available MiB of disk to allocate to containers.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "min(avg(firehose_value_metric_rep_capacity_remaining_disk{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Least Available Disk"
    },
    {
     "expr": "max(avg(firehose_value_metric_rep_capacity_remaining_disk{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Most Available Disk"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_disk{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Total Available Disk"
    }
   ]
  },
  {
   "title": "Available Containers",
   "type": "graph",
   "description": "Available number of containers.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(avg(firehose_value_metric_rep_capacity_remaining_containers{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Least Available Containers"
    },
    {
     "expr": "max(avg(firehose_value_metric_rep_capacity_remaining_containers{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Cell with Most Available Containers"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_containers{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Total Available Containers"
    }
   ]
  },
  {
   "title": "BBS Requests per Second (max)",
   "type": "graph",
   "description": "Max number of requests per second received by the BBS.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_bbs_request_count_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "Req/Sec"
    }
   ]
  },
  {
   "title": "BBS Request Latency (max)",
   "type": "graph",
   "description": "Max time in nanoseconds that the BBS took to handle requests to its API endpoints.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_bbs_request_latency{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "BBS Convergence Duration (max)",
   "type": "graph",
   "description": "Max time in nanoseconds that the BBS took to run its LRP and Task convergence pass. Emitted when LRP and Task convergence runs.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_bbs_convergence_lrp_duration{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})",
     "legendFormat": "LRPs"
    },
    {
     "expr": "max(firehose_value_metric_bbs_convergence_task_duration{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Router Requests per Second (max)",
   "type": "graph",
   "description": "Max number of requests per second received by the Gorouter.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_gorouter_total_requests_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "Req/Sec"
    }
   ]
  },
  {
   "title": "Router Latency (max)",
   "type": "graph",
   "description": "Max time in nanoseconds that the Gorouter took to handle requests to its application endpoints.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_gorouter_latency{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Router Bad Gateway Responses per Second (max)",
   "type": "graph",
   "description": "Max number of Gorouter's HTTP Bad Gateway responses per second.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_gorouter_bad_gateways_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "Resp/sec"
    }
   ]
  },
  {
   "title": "CC Requests Completed per Second (max)",
   "type": "graph",
   "description": "Max number of requests per second received by the Cloud Controller.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_value_metric_cc_requests_completed{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "Req/sec"
    }
   ]
  },
  {
   "title": "CC Job Queue Length (max)",
   "type": "graph",
   "description": "Max number of background jobs in the queues that have yet to run for the first time.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_cc_job_queue_length_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})",
     "legendFormat": "Length"
    }
   ]
  },
  {
   "title": "CC 5xx Responses per Second (max)",
   "type": "graph",
   "description": "Max number of CC's HTTP 5xx responses per second.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_value_metric_cc_http_status_5_xx{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "5xx resp/sec"
    }
   ]
  },
  {
   "title": "Auctions per Second (max)",
   "type": "graph",
   "description": "Max number of LRP instances and Tasks that the auctioneer successfully placed on Diego cells per second",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_started_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "LRPs"
    },
    {
     "expr": "max(rate(firehose_counter_event_auctioneer_auctioneer_task_auctions_started_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Auctions",
   "type": "graph",
   "description": "Cumulative number of LRP instances and Tasks that the auctioneer successfully of failed to place on Diego cells.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_started_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Started LPRs"
    },
    {
     "expr": "sum(avg(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_failed_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Failed LRPs"
    },
    {
     "expr": "sum(avg(firehose_counter_event_auctioneer_auctioneer_task_auctions_started_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Started Tasks"
    },
    {
     "expr": "sum(avg(firehose_counter_event_auctioneer_auctioneer_task_auctions_failed_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Failed Tasks"
    }
   ]
  },
  {
   "title": "Fetch States Duration (max)",
   "type": "graph",
   "description": "Max time in nanoseconds that the auctioneer took to fetch state from all the cells when running its auction.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_auctioneer_auctioneer_fetch_states_duration{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Desired LRP Sync Duration (max)",
   "type": "graph",
   "description": "Max time in nanoseconds that the nsync-bulker took to synchronize CF apps and Diego DesiredLRPs",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(firehose_value_metric_nsync_bulker_desired_lrp_sync_duration{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "LRPs Velocity (max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_value_metric_bbs_lr_ps_desired{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[30m]))",
     "legendFormat": "LRPs Desired"
    },
    {
     "expr": "max(rate(firehose_value_metric_bbs_lr_ps_running{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[30m]))",
     "legendFormat": "LRPs Running"
    }
   ]
  },
  {
   "title": "Failed Staging Requests",
   "type": "graph",
   "description": "Number of failed staging tasks.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(avg_over_time(firehose_counter_event_stager_staging_requests_failed_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[1h]))",
     "legendFormat": "1hr Avg Failed Requests"
    }
   ]
  },
  {
   "title": "Messages per Second Received/Dropped by Doppler Listeners  (max)",
   "type": "graph",
   "description": "Max number of messages received & dropped across all of Doppler listeners per second.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_doppler_server_listeners_total_received_message_count_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "max(rate(firehose_counter_event_doppler_server_truncating_buffer_total_dropped_messages_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "Dropped"
    }
   ]
  },
  {
   "title": "Metron Agent Envelopes per Second (max)",
   "type": "graph",
   "description": "Max number of messages marshalled sent and messages unmarshalled received per second.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_metron_agent_dropsonde_marshaller_sent_envelopes_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "Marshalled"
    },
    {
     "expr": "max(rate(firehose_counter_event_metron_agent_dropsonde_unmarshaller_received_envelopes_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "Unmarshalled"
    }
   ]
  },
  {
   "title": "Metron Agent Messages Sent per Second (max)",
   "type": "graph",
   "description": "Max number of sent messages  per second to Doppler",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_metron_agent_udp_sent_message_count_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "UDP"
    },
    {
     "expr": "max(rate(firehose_counter_event_metron_agent_tcp_sent_message_count_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "TCP"
    },
    {
     "expr": "max(rate(firehose_counter_event_metron_agent_tls_sent_message_count_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "TLS"
    },
    {
     "expr": "max(rate(firehose_counter_event_metron_agent_grpc_sent_message_count_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[5m]))",
     "legendFormat": "GRPC"
    }
   ]
  }
 ]
}