{
 "title": "CF: Metron Agent - Doppler",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_counter_event_metron_agent_dropsonde_marshaller_sent_envelopes_total, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_counter_event_metron_agent_dropsonde_marshaller_sent_envelopes_total{environment=~\"$environment\"}, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages Sent to Doppler",
   "type": "timeseries",
   "description": "Cumulative number of sent messages to Doppler.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_udp_sent_message_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_tcp_sent_message_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_tls_sent_message_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "TLS"
    },
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_grpc_sent_message_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "GRPC"
    }
   ]
  },
  {
   "title": "Bytes Sent to Doppler",
   "type": "timeseries",
   "description": "Cumulative number of sent bytes to Doppler.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_udp_sent_byte_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_tcp_sent_byte_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_tls_sent_byte_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "TLS"
    },
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_grpc_sent_byte_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "GRPC"
    }
   ]
  },
  {
   "title": "Errors Writing  to Doppler",
   "type": "timeseries",
   "description": "Cumulative number of errors if writing to Doppler fails.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_udp_send_error_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_tcp_send_error_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_tls_send_error_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "TLS"
    },
    {
     "expr": "sum(avg(firehose_counter_event_metron_agent_grpc_send_error_count_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "GRPC"
    }
   ]
  }
 ]
}