{
 "title": "CF: Metron Agent",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_counter_event_loggregator_metron_egress_total, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_counter_event_loggregator_metron_egress_total{environment=~\"$environment\"}, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Metron Egress",
   "type": "graph",
   "description": "Cumulative number of messages sent.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(firehose_counter_event_loggregator_metron_egress_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Sent (Marshaller)"
    }
   ]
  },
  {
   "title": "Metron Egress by Job",
   "type": "graph",
   "description": "Messages sent by job.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(firehose_counter_event_loggregator_metron_egress_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(environment, bosh_deployment, bosh_job_name)",
     "legendFormat": "{{bosh_job_name}}"
    }
   ]
  },
  {
   "title": "Metron Ingress Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(firehose_counter_event_loggregator_metron_ingress_total{environment=~\"$environment\",bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Messages"
    }
   ]
  }
 ]
}