{
 "title": "CF: Organization Summary",
 "tags": [ "cf" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(cf_organization_info, environment)"
    }
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(cf_organization_info{environment=~\"$environment\"}, deployment)"
    }
   },
   {
    "name": "cf_organization_name",
    "label": "Organization",
    "query": {
     "query": "label_values(cf_organization_info{environment=~\"$environment\",deployment=~\"${bosh_deployment}\"}, organization_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "timeseries",
   "description": "Total number of running Instances and Quota for this Organization.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg(cf_application_instances{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\",state=\"STARTED\"}) by(application_id))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(cf_organization_total_app_instances_quota{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "State of Applications",
   "type": "piechart",
   "description": "State of Applications at this Organization.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(cf_application_info{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\"}) by(application_id, state)) by(state) ",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Total Memory Used by running instances and Quota for this Organization.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(avg(cf_application_memory_mb{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\"} * on (application_id) cf_application_instances{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\",state=\"STARTED\"}) by(application_id))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(cf_organization_total_memory_mb_quota{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "description": "Total Disk allocated to running instances for this Organization.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(avg(cf_application_disk_quota_mb{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\"} * on (application_id) cf_application_instances{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\",state=\"STARTED\"}) by(application_id))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "piechart",
   "description": "Stacks used at this Organization.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(cf_application_info{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\"}) by(application_id, stack_id)) by(stack_id) * on(stack_id) group_left(stack_name) count(cf_stack_info{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(stack_id, stack_name)",
     "legendFormat": "{{ stack_name }}"
    }
   ]
  },
  {
   "title": "Buildpacks",
   "type": "piechart",
   "description": "Buildpacks used at this Organization.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(cf_application_info{environment=~\"$environment\",deployment=~\"${bosh_deployment}[-0-9a-f]*\",organization_name=~\"$cf_organization_name\"}) by(application_id, buildpack)) by(buildpack)",
     "legendFormat": "{{ buildpack }}"
    }
   ]
  }
 ]
}