{
 "title": "CF: Router v2",
 "tags": [
  "cf",
  "router",
  "v2"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_counter_event_gorouter_total_requests_total, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rate Requests per second",
   "type": "graph",
   "description": "Successful and failed requests received per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(rate(firehose_counter_event_gorouter_total_requests_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg(rate(firehose_counter_event_gorouter_rejected_requests_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Rate Responses per second",
   "type": "graph",
   "description": "HTTP responses per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(rate(firehose_counter_event_gorouter_responses_2_xx_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(avg(rate(firehose_counter_event_gorouter_responses_3_xx_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(avg(rate(firehose_counter_event_gorouter_responses_4_xx_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(avg(rate(firehose_counter_event_gorouter_responses_5_xx_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "description": "Cumulative number of successful and failed requests received. Emitted every 5 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_gorouter_total_requests_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg(firehose_counter_event_gorouter_rejected_requests_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Total Responses",
   "type": "graph",
   "description": "Cumulative number of HTTP responses. Emitted every 5 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_counter_event_gorouter_responses_2_xx_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(avg(firehose_counter_event_gorouter_responses_3_xx_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(avg(firehose_counter_event_gorouter_responses_4_xx_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(avg(firehose_counter_event_gorouter_responses_5_xx_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Time in milliseconds that the Gorouter took to handle requests to its application endpoints. Emitted per router request.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_gorouter_latency{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Route Lookup Time",
   "type": "graph",
   "description": "Route Lookup time.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_gorouter_route_lookup_time{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Rate Register Messages Received per second",
   "type": "graph",
   "description": "Route registration messages received per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_gorouter_registry_message_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Total Register Messages Received",
   "type": "graph",
   "description": "Number of route registration messages received. Emitted per route-register message.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_counter_event_gorouter_registry_message_total{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Total Routes Registered",
   "type": "graph",
   "description": "Number of routes registered. Emitted every 30 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_gorouter_total_routes{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})",
     "legendFormat": "Routes"
    }
   ]
  }
 ]
}