{
 "title": "CF: Summary v2",
 "tags": [
  "cf",
  "v2"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(cf_organization_info, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "singlestat",
   "description": "Number of Cloud Foundry Users",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(firehose_value_metric_cc_total_users{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})"
    }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "description": "Number of Cloud Foundry Users",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_cc_total_users{bosh_deployment=~\"${bosh_deployment}[-0-9a-f]*\"})",
     "legendFormat": "Number of Users"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "singlestat",
   "description": "Number of Cloud Foundry Applications",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "graph",
   "description": "Number of Cloud Foundry Applications",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_application_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))",
     "legendFormat": "Number of Applications"
    }
   ]
  },
  {
   "title": "Organizations",
   "type": "singlestat",
   "description": "Number of Cloud Foundry Organizations",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_organization_info{deployment=~\"${bosh_deployment}\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Organizations",
   "type": "graph",
   "description": "Number of Cloud Foundry Organizations",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_organization_info{deployment=~\"${bosh_deployment}\"}) without(instance))",
     "legendFormat": "Number of Organizations"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "singlestat",
   "description": "Number of Cloud Foundry  Routes",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_route_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "graph",
   "description": "Number of Cloud Foundry  Routes",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_route_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))",
     "legendFormat": "Number of Routes"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "description": "Number of Cloud Foundry Services",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_service_info{deployment=~\"${bosh_deployment}\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Services",
   "type": "graph",
   "description": "Number of Cloud Foundry Services",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_service_info{deployment=~\"${bosh_deployment}\"}) without(instance))",
     "legendFormat": "Number of Services"
    }
   ]
  },
  {
   "title": "Service Instances",
   "type": "singlestat",
   "description": "Number of Cloud Foundry Service Instances",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_service_instance_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Service Instances",
   "type": "graph",
   "description": "Number of Cloud Foundry Service Instances",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_service_instance_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))",
     "legendFormat": "Number of Service Instances"
    }
   ]
  },
  {
   "title": "Service Bindings",
   "type": "singlestat",
   "description": "Total number of Cloud Foundry Service Bindings",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_service_binding_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Service Bindings",
   "type": "graph",
   "description": "Number of Cloud Foundry Service Bindings",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_service_binding_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))",
     "legendFormat": "Number of Service Bindings"
    }
   ]
  },
  {
   "title": "Spaces",
   "type": "singlestat",
   "description": "Total number of Cloud Foundry Spaces",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_space_info{deployment=~\"${bosh_deployment}\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Spaces",
   "type": "graph",
   "description": "Number of Cloud Foundry Spaces",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_space_info{deployment=~\"${bosh_deployment}\"}) without(instance))",
     "legendFormat": "Number of Spaces"
    }
   ]
  },
  {
   "title": "Security Groups",
   "type": "singlestat",
   "description": "Number of Cloud Foundry Security Groups",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_security_group_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Security Groups",
   "type": "graph",
   "description": "Number of Cloud Foundry Security Groups",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_security_group_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))",
     "legendFormat": "Number of Security Groups"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "singlestat",
   "description": "Number of Cloud Foundry Stacks",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_stack_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "graph",
   "description": "Number of Cloud Foundry Stacks",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_stack_info{deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) without(instance))",
     "legendFormat": "Number of Stacks"
    }
   ]
  }
 ]
}