{
 "title": "CF: Space Summary v2",
 "tags": [
  "cf",
  "v2"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(cf_space_info, deployment)"
   },
   {
    "name": "cf_organization_name",
    "label": "Organization",
    "query": "label_values(cf_organization_info{deployment=~\"${bosh_deployment}\"}, organization_name)"
   },
   {
    "name": "cf_organization_id",
    "label": "Organization ID",
    "query": "label_values(cf_organization_info{deployment=~\"${bosh_deployment}\", organization_name=~\"$cf_organization_name\"}, organization_id)"
   },
   {
    "name": "cf_space_name",
    "label": "Space",
    "query": "label_values(cf_space_info{deployment=~\"${bosh_deployment}\", organization_id=~\"$cf_organization_id\"}, space_name)"
   },
   {
    "name": "cf_space_id",
    "label": "Space ID",
    "query": "label_values(cf_space_info{deployment=~\"${bosh_deployment}\", organization_id=~\"$cf_organization_id\", space_name=~\"$cf_space_name\"}, space_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "stat",
   "description": "Total number of running Instances and Quota for this Space.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(cf_application_instances{deployment=~\"${bosh_deployment}\",organization_id=~\"$cf_organization_id\",space_name=~\"$cf_space_name\",state=\"STARTED\"}) by(application_id))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Total Memory Used by running instances and Quota for this Space.",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(cf_application_memory_mb{deployment=~\"${bosh_deployment}\",organization_id=~\"$cf_organization_id\",space_name=~\"$cf_space_name\"} * on (application_id) cf_application_instances{deployment=~\"${bosh_deployment}\",organization_id=~\"$cf_organization_id\",space_name=~\"$cf_space_name\",state=\"STARTED\"}) by(application_id))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Service Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(cf_service_instance_info{deployment=~\"${bosh_deployment}\",space_id=~\"$cf_space_id\"}) by(service_instance_id))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(cf_route_info{deployment=~\"${bosh_deployment}\",space_id=~\"$cf_space_id\"}) by(route_id))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "description": "Total Disk allocated to running instances for this Space.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(cf_application_disk_quota_mb{deployment=~\"${bosh_deployment}\",organization_id=~\"$cf_organization_id\",space_name=~\"$cf_space_name\"} * on (application_id) cf_application_instances{deployment=~\"${bosh_deployment}\",organization_id=~\"$cf_organization_id\",space_name=~\"$cf_space_name\",state=\"STARTED\"}) by(application_id))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "grafana-piechart-panel",
   "description": "Stacks used at this Space.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_application_info{deployment=~\"${bosh_deployment}\",organization_id=~\"$cf_organization_id\",space_name=~\"$cf_space_name\"}) by(application_id, stack_id)) by(stack_id) * on(stack_id) group_left(stack_name) count(cf_stack_info{deployment=~\"${bosh_deployment}\"}) by(stack_id, stack_name)",
     "legendFormat": "{{ stack_name }}"
    }
   ]
  },
  {
   "title": "Buildpacks",
   "type": "grafana-piechart-panel",
   "description": "Buildpacks used at this Space.",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_application_info{deployment=~\"${bosh_deployment}\",organization_id=~\"$cf_organization_id\",space_name=~\"$cf_space_name\"}) by(application_id, buildpack)) by(buildpack)",
     "legendFormat": "{{ buildpack }}"
    }
   ]
  },
  {
   "title": "State of Applications",
   "type": "grafana-piechart-panel",
   "description": "State of Applications at this Space.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(cf_application_info{deployment=~\"${bosh_deployment}\",organization_id=~\"$cf_organization_id\",space_name=~\"$cf_space_name\"}) by(application_id, state)) by(state) ",
     "legendFormat": "{{ state }}"
    }
   ]
  }
 ]
}