{
 "title": "CF: Services v2",
 "tags": [
  "cf",
  "v2"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(cf_service_info, deployment)"
   },
   {
    "name": "service_name",
    "label": "Service",
    "query": "label_values(cf_service_info{ deployment=~\"${bosh_deployment}\"}, service_label)"
   },
   {
    "name": "service_id",
    "query": "label_values(cf_service_info{ deployment=~\"${bosh_deployment}\", service_label=\"$service_name\"}, service_id)"
   },
   {
    "name": "service_plan_name",
    "label": "Service Plan",
    "query": "label_values(cf_service_plan_info{ deployment=~\"${bosh_deployment}\", service_id=~\"$service_id\"}, service_plan_name)"
   },
   {
    "name": "service_plan_id",
    "query": "label_values(cf_service_plan_info{ deployment=~\"${bosh_deployment}\", service_id=~\"$service_id\", service_plan_name=\"$service_plan_name\"}, service_plan_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Instances",
   "type": "singlestat",
   "description": "Number of Service Instances",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(min(cf_service_instance_info{ deployment=~\"${bosh_deployment}[-0-9a-f]*\", service_plan_id=~\"$service_plan_id\"}) by(service_instance_id))"
    }
   ]
  },
  {
   "title": "Service Instances Names",
   "type": "table-old",
   "description": "Name of the Services Instances",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(cf_service_instance_info{ deployment=~\"${bosh_deployment}[-0-9a-f]*\", service_plan_id=~\"$service_plan_id\"}) by(service_instance_name, space_id) * on(space_id) group_left(space_name, organization_id) count(cf_space_info{ deployment=~\"${bosh_deployment}\"}) by(space_id, space_name, organization_id) * on(organization_id) group_left(organization_name) count(cf_organization_info{ deployment=~\"${bosh_deployment}\"}) by(organization_id, organization_name)",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ service_instance_name }}"
    }
   ]
  },
  {
   "title": "Service Bindings",
   "type": "singlestat",
   "description": "Number of Service Bindings",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(min(cf_service_binding_info{ deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(service_binding_id, service_instance_id) * on(service_instance_id) group_left(service_plan_id) min(cf_service_instance_info{ deployment=~\"${bosh_deployment}[-0-9a-f]*\", service_plan_id=~\"$service_plan_id\"}) by(service_instance_id, service_plan_id)) "
    }
   ]
  },
  {
   "title": "Bound Applications",
   "type": "table-old",
   "description": "Name of the Bound Applications",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "count(cf_service_binding_info{ deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(application_id, service_binding_id, service_instance_id) * on(service_instance_id) group_left(service_instance_name) count(cf_service_instance_info{ deployment=~\"${bosh_deployment}[-0-9a-f]*\", service_plan_id=~\"$service_plan_id\"}) by(service_instance_id, service_instance_name) * on(application_id) group_left(organization_name, space_name, application_name)  count(cf_application_info{ deployment=~\"${bosh_deployment}[-0-9a-f]*\"}) by(organization_name, space_name, application_id, application_name)",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ service_instance_name }} <- {{ application_name }}"
    }
   ]
  }
 ]
}