{
 "title": "Prometheus: Cloud Foundry Exporter",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(cf_last_organizations_scrape_timestamp, environment)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(cf_last_organizations_scrape_timestamp{environment=~\"$environment\"}, deployment)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cf_last_organizations_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Applications Scrape Duration",
   "type": "timeseries",
   "description": "How long it took to scrape Applications from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cf_last_applications_scrape_duration_seconds{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Applications Scrape",
   "type": "stat",
   "description": "When was the last Applications scrape from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(cf_last_applications_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Applications Scrape Status",
   "type": "stat",
   "description": "Whether the last scrape of Application metrics from Cloud Foundry resulted in an error.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_last_applications_scrape_error{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Organizations Scrape Duration",
   "type": "timeseries",
   "description": "How long it took to scrape Organizations from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cf_last_organizations_scrape_duration_seconds{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Organizations Scrape",
   "type": "stat",
   "description": "When was the last Organizations scrape from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(cf_last_organizations_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Organizations Scrape Status",
   "type": "stat",
   "description": "Whether the last scrape of Organization metrics from Cloud Foundry resulted in an error.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_last_organizations_scrape_error{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Routes Scrape Duration",
   "type": "timeseries",
   "description": "How long it took to scrape Routes  from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cf_last_routes_scrape_duration_seconds{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Routes Scrape",
   "type": "stat",
   "description": "When was the last Routes scrape from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(cf_last_routes_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Routes Scrape Status",
   "type": "stat",
   "description": "Whether the last scrape of Route metrics from Cloud Foundry resulted in an error.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_last_routes_scrape_error{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Services Scrape Duration",
   "type": "timeseries",
   "description": "How long it took to scrape Services from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cf_last_services_scrape_duration_seconds{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Services Scrape",
   "type": "stat",
   "description": "When was the last Services scrape from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(cf_last_services_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Services Scrape Status",
   "type": "stat",
   "description": "Whether the last scrape of Service metrics from Cloud Foundry resulted in an error.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_last_services_scrape_error{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Service Bindings Scrape Duration",
   "type": "timeseries",
   "description": "How long it took to scrape Service Bindings from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cf_last_service_bindings_scrape_duration_seconds{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Service Bindings Scrape",
   "type": "stat",
   "description": "When was the last Service Bindings scrape from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(cf_last_service_bindings_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Service Bindings Scrape Status",
   "type": "stat",
   "description": "Whether the last scrape of Service Bindings metrics from Cloud Foundry resulted in an error.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_last_service_bindings_scrape_error{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Service Instances Scrape Duration",
   "type": "timeseries",
   "description": "How long it took to scrape Service Instances from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cf_last_service_instances_scrape_duration_seconds{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Service Instances Scrape",
   "type": "stat",
   "description": "When was the last Service Instances scrape from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(cf_last_service_instances_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Service Instances Scrape Status",
   "type": "stat",
   "description": "Whether the last scrape of Service Instance metrics from Cloud Foundry resulted in an error.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_last_service_instances_scrape_error{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Service Plans Scrape Duration",
   "type": "timeseries",
   "description": "How long it took to scrape Service Plans from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cf_last_service_plans_scrape_duration_seconds{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Service Plans Scrape",
   "type": "stat",
   "description": "When was the last Service Plans scrape from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(cf_last_service_plans_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Service Plans Scrape Status",
   "type": "stat",
   "description": "Whether the last scrape of Service Plans metrics from Cloud Foundry resulted in an error.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_last_service_plans_scrape_error{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Spaces Scrape Duration",
   "type": "timeseries",
   "description": "How long it took to scrape Spaces from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cf_last_spaces_scrape_duration_seconds{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Spaces Scrape",
   "type": "stat",
   "description": "When was the last Spaces scrape from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(cf_last_spaces_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Spaces Scrape Status",
   "type": "stat",
   "description": "Whether the last scrape of Space metrics from Cloud Foundry resulted in an error.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_last_spaces_scrape_error{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Security Groups Scrape Duration",
   "type": "timeseries",
   "description": "How long it took to scrape Security Groups from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cf_last_security_groups_scrape_duration_seconds{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Security Groups Scrape",
   "type": "stat",
   "description": "When was the last Security Groups scrape from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(cf_last_security_groups_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Security Groups Scrape Status",
   "type": "stat",
   "description": "Whether the last scrape of Security Group metrics from Cloud Foundry resulted in an error.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_last_security_groups_scrape_error{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Stacks Scrape Duration",
   "type": "timeseries",
   "description": "How long it took to scrape Stacks from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cf_last_stacks_scrape_duration_seconds{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Stacks Scrape",
   "type": "stat",
   "description": "When was the last Stacks scrape from Cloud Foundry.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(cf_last_stacks_scrape_timestamp{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Stacks Scrape Status",
   "type": "stat",
   "description": "Whether the last scrape of Stack metrics from Cloud Foundry resulted in an error.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_last_stacks_scrape_error{environment=~\"$environment\",deployment=~\"$deployment\",instance=~\"$instance\"})"
    }
   ]
  }
 ]
}